Warning: truncated output (original token count: 32438)
Total output lines: 493

export type Article = {
  id: number;
  category: "ai" | "social" | "brand";
  subcategory: string;
  platforms?: string[];
  daily?: boolean;
  source: string;
  date: string;
  title: string;
  titleZh: string;
  summary: string;
  summaryZh: string;
  digest: string;
  digestZh: string;
  url: string;
  image: string;
};

export const articles: Article[] = [
  {
    id: 1, category: "ai", subcategory: "Ad tech",
    source: "MarTech", date: "July 27, 2026",
    title: "ChatGPT Ads adds conversion bidding and stronger measurement",
    titleZh: "ChatGPT 广告新增转化出价与更强衡量能力",
    summary: "OpenAI is adding conversion-focused bidding and stronger measurement to ChatGPT Ads, bringing the emerging format closer to the workflows performance marketers already use on Google and Meta.",
    summaryZh: "OpenAI 正在为 ChatGPT 广告加入以转化为目标的出价和更完善的衡量能力，让这一新广告形式更接近营销人员在 Google 和 Meta 上熟悉的投放流程。",
    digest: "The update gives advertisers a clearer way to optimize campaigns toward business outcomes instead of simply buying exposure. Better conversion signals should also make it easier to compare ChatGPT Ads with established paid-media channels. The change does not prove that the format can yet match their scale, but it makes testing more practical: marketers can define an outcome, monitor performance and let bidding respond to conversion data rather than manually judging an unfamiliar placement.",
    digestZh: "此次更新让广告主可以更明确地围绕业务结果优化广告，而不只是购买曝光。更好的转化信号也有助于把 ChatGPT 广告与成熟的付费媒体渠道进行比较。这并不意味着它已经具备同等规模，但会让测试变得更实际：营销人员能够先定义目标，再通过转化数据观察并优化投放。",
    url: "https://martech.org/chatgpt-ads-adds-conversion-bidding-and-stronger-measurement/", image: "",
  },
  {
    id: 2, category: "ai", subcategory: "AI marketing tools",
    source: "MarTech", date: "July 27, 2026",
    title: "Why your AI-review process is going to fail",
    titleZh: "为什么你的 AI 审核流程注定会失败",
    summary: "Fluent AI output can look correct even when it is not. The article argues for review systems that combine prior knowledge, deterministic checks and human judgment instead of relying on surface plausibility.",
    summaryZh: "AI 输出即使不正确，也可能表达得非常流畅。文章建议把先验知识、确定性检查和人工判断结合起来，而不是只凭内容“看起来可信”就通过审核。",
    digest: "The core problem is that language models optimize for plausible responses, while reviewers often mistake confidence and fluency for evidence. A stronger process begins with what the team already knows, treats the AI response as one new piece of evidence and uses reliable tools to verify claims that can be checked. Human judgment remains essential for ambiguity, context and risk. The result is a layered review process rather than a single final approval step.",
    digestZh: "核心问题是语言模型擅长生成“看起来合理”的回答，而审核者很容易把自信、流畅的表达误认为证据。更可靠的流程应先明确团队已有的知识，把 AI 回答当成一条新证据，再用可重复的工具验证能够核实的事实；涉及语境、模糊性与风险时仍需人工判断。审核因此应成为分层流程，而不是最后一次简单批准。",
    url: "https://martech.org/why-your-ai-review-process-is-going-to-fail/", image: "",
  },
  {
    id: 3, category: "ai", subcategory: "AI marketing tools",
    source: "MarTech", date: "July 27, 2026",
    title: "AI is pushing composability beyond software",
    titleZh: "AI 正在把“可组合性”推向软件之外",
    summary: "AI systems are beginning to coordinate software, people and decisions as modular resources, shifting the idea of a composable stack from connected tools to connected work.",
    summaryZh: "AI 系统正在把软件、人员和决策作为可组合的资源进行协调，使“可组合技术栈”从连接工具进一步发展为连接完整工作流程。",
    digest: "Traditional composability lets teams assemble software components around changing needs. AI extends that model by reasoning about a task, planning steps and coordinating actions across SaaS tools and human contributors. For marketing teams, the important shift is from asking which application owns a workflow to asking how the work can be broken into modules, where intelligence is useful and where people should keep control.",
    digestZh: "传统的可组合性让团队按照不断变化的需求组合不同软件组件。AI 则进一步理解任务、规划步骤，并在 SaaS 工具和人员之间协调行动。对营销团队而言，关键变化不是“哪个应用负责这条流程”，而是如何把工作拆成模块、在哪些环节使用智能、哪些决策仍由人掌控。",
    url: "https://martech.org/ai-is-pushing-composability-beyond-software/", image: "",
  },
  {
    id: 4, category: "ai", subcategory: "AI marketing tools",
    source: "Marketing Dive", date: "July 27, 2026",
    title: "Marketers’ latest AI conundrum: An environmental footprint left unmeasured",
    titleZh: "营销人员最新的 AI 难题：尚未被衡量的环境足迹",
    summary: "As brands expand generative AI use, many still lack a reliable way to measure the technology’s energy and environmental cost alongside productivity gains.",
    summaryZh: "随着品牌扩大生成式 AI 的使用，许多团队仍缺少可靠方法，无法在衡量效率提升的同时计算其能源消耗与环境成本。",
    digest: "Generative AI is being embedded in creative and operational workflows faster than its environmental impact can be measured. That creates a reporting gap for brands with sustainability commitments: productivity benefits are visible, but energy use and emissions are often opaque. The story highlights the need for clearer supplier data, consistent measurement and deliberate decisions about when AI use creates enough value to justify its cost.",
    digestZh: "生成式 AI 进入创意与运营流程的速度，已经超过企业衡量其环境影响的能力。对于承诺可持续发展的品牌，这会形成报告缺口：效率提升清晰可见，能源使用和排放却往往不透明。文章指出，品牌需要供应商提供更清晰的数据、建立一致的衡量方法，并认真判断哪些场景的 AI 价值足以抵消其成本。",
    url: "https://www.marketingdive.com/news/marketers-latest-ai-conundrum-an-environmental-footprint-left-unmeasured/826137/", image: "",
  },
  {
    id: 5, category: "ai", subcategory: "Ad tech",
    source: "MediaPost", date: "July 27, 2026",
    title: "Asahi merges Japanese artistry with AI for Piccadilly Lights takeover",
    titleZh: "朝日啤酒以日本艺术融合 AI，登陆皮卡迪利灯光大屏",
    summary: "Asahi used AI-supported creative production to translate Japanese visual craft into a large-format digital-out-of-home experience at London’s Piccadilly Lights.",
    summaryZh: "朝日啤酒借助 AI 创意制作，把日本视觉工艺转化为伦敦皮卡迪利灯光大屏上的大型数字户外体验。",
    digest: "The campaign combines Japanese-inspired visual language with AI-enabled production for one of London’s most prominent digital screens. Its value is not simply that AI was used, but that the technology helped adapt a specific brand world to the scale, motion and public context of digital out-of-home. It is a useful example of treating AI as a production layer in service of a recognizable idea rather than making the tool itself the creative concept.",
    digestZh: "该活动把日式视觉语言与 AI 制作结合，呈现在伦敦最醒目的数字户外屏幕之一。重点不只是“使用了 AI”，而是技术帮助品牌把独特视觉世界适配到数字户外所需的尺度、动态与公共空间语境。它展示了如何让 AI 成为服务于品牌创意的制作层，而不是把工具本身当成创意主题。",
    url: "https://www.mediapost.com/publications/article/416801/asahi-merges-japanese-artistry-with-ai-for-piccadi.html", image: "",
  },
  {
    id: 6, category: "social", subcategory: "Social Media Strategy", platforms: ["Cross-platform"],
    source: "Sprout Social", date: "July 9, 2026",
    title: "How to build a cross-network brand monitoring strategy on social",
    titleZh: "如何建立跨平台社交品牌监测策略",
    summary: "A framework for replacing isolated mention tracking with a unified monitoring system that connects social conversations, forums, reviews and news to customer care, product and reputation decisions.",
    summaryZh: "这套框架帮助品牌从零散的提及追踪升级为统一监测系统，把社交对话、论坛、评论和新闻连接到客服、产品与声誉决策。",
    digest: "Social narratives now move between TikTok, LinkedIn, Reddit, review sites and news faster than teams organized around one channel can follow. Sprout Social recommends mapping every relevant network, defining the brand, product, executive, competitor and category terms to track, and centralizing those signals in one operating view. Objectives should be explicit—brand health, crisis detection, campaign performance, product feedback or competitive intelligence—so the data produces decisions instead of noise. The article then moves beyond retrospective dashboards toward agentic monitoring: always-on systems can identify unusual volume, sentiment drops and emerging themes, then route alerts to the right team. Human judgment remains responsible for response, nuance and escalation. A useful program therefore combines unified data, clear thresholds, automated detection and internal pathways that send product issues to product teams, care problems to service teams and reputational risks to communications leaders.",
    digestZh: "社交叙事会在 TikTok、LinkedIn、Reddit、评论网站和新闻之间快速流动，按单一渠道组织的团队很难完整追踪。Sprout Social 建议先梳理所有相关网络，明确需要监测的品牌、产品、高管、竞争对手和品类关键词，再把这些信号集中到统一视图。监测目标必须清晰，例如品牌健康、危机发现、活动表现、产品反馈或竞争情报，才能让数据真正产生决策。文章进一步提出从回顾型仪表盘转向智能体监测：持续运行的系统可以识别异常声量、情绪下降和新兴主题，并把提醒发送给正确团队。人工仍负责语境判断、回应与升级。有效方案因此需要统一数据、清晰阈值、自动检测和内部传递路径。",
    url: "https://sproutsocial.com/insights/cross-network-brand-monitoring/", image: "",
  },
  {
    id: 7, category: "social", subcategory: "Social Media Strategy", platforms: ["Cross-platform"],
    source: "Sprout Social", date: "July 23, 2026",
    title: "A tactical guide to social media comments and responses",
    titleZh: "社交媒体评论与回应的实战指南",
    summary: "Comment sections are becoming customer experience, community and product-discovery spaces. The guide turns response work into a structured system of triage, tone, escalation and measurement.",
    summaryZh: "评论区正在成为客服体验、社群建设和产品发现的重要场所。文章把回复工作转化为包含分类、语气、升级和衡量的结构化系统。",
    digest: "The article argues that comments are no longer a secondary reaction beneath content. They are a real-time measure of sentiment, a customer-care channel and a place where people search for unfiltered product opinions. Sprout Social recommends a dual operating model: daily workflows for social and care teams, supported by strategic guardrails from communications leaders. Incoming comments should be triaged into engagement, service, sales or risk; replies should be fast but human, personalized and consistent with category expectations. Teams also need rules for when to reply publicly, move a conversation into direct messages, monitor without responding or escalate to legal and communications. Positive comments can reveal advocates and reusable insight, while negative feedback needs empathy, resolution tracking and prepared crisis protocols. The broader lesson is that community management should be designed like a service operation—with ownership, response standards, saved context and escalation—without reducing every interaction to a robotic script.",
    digestZh: "文章认为，评论不再只是内容下方的次要反馈，而是实时情绪指标、客户服务渠道，也是消费者寻找真实产品意见的地方。Sprout Social 建议采用双层运营模式：社交与客服团队负责日常流程，传播负责人提供策略护栏。评论应被快速分类为互动、服务、销售或风险；回复要及时，但仍需自然、个性化，并符合品类语境。团队还要明确何时公开回复、转入私信、暂不回应或升级至法务与传播部门。积极评论可以发现品牌拥护者与可复用洞察，负面反馈则需要同理心、解决记录和预设危机流程。核心启示是：社群管理应像服务运营一样具备负责人、回复标准、历史语境与升级机制，同时避免把互动变成机械话术。",
    url: "https://sproutsocial.com/insights/social-media-comments/", image: "",
  },
  {
    id: 8, category: "social", subcategory: "Social Media Strategy", platforms: ["Reddit"],
    source: "The Goat Agency", date: "May 13, 2026",
    title: "r/InfluencerMarketing: Reddit’s Nathan O’Connor on how brands can show up on Reddit",
    titleZh: "Reddit 的 Nathan O’Connor：品牌应如何进入 Reddit",
    summary: "A platform-focused discussion of Reddit culture, paid and organic activation, brand safety, AI search and why marketers must understand communities before trying to participate.",
    summaryZh: "这篇平台专题讨论 Reddit 文化、付费与自然运营、品牌安全和 AI 搜索，并解释品牌为什么必须先理解社群，再尝试参与。",
    digest: "The Goat Agency’s conversation with Reddit partnership leader Nathan O’Connor treats Reddit as a network of communities rather than a conventional broadcast feed. It explains the platform’s terminology, the role of subreddit culture and why brands often overestimate negative sentiment while underestimating the value of candid discussion. The episode separates paid advertising from organic participation and examines when each can support a brand. Successful activation begins with understanding the language, norms and concerns of a relevant community; a promotional message that ignores context can feel intrusive even when its targeting is technically correct. The discussion also covers brand safety, emerging creator behavior on Reddit and the platform’s growing influence on search. Because Reddit conversations increasingly appear in AI-generated answers, useful participation can contribute to both community credibility and wider discovery. The strategic lesson is to research first, add genuine value and treat trust as an accumulated asset rather than expecting a single campaign to manufacture acceptance.",
    digestZh: "The Goat Agency 与 Reddit 合作负责人 Nathan O’Connor 的对话把 Reddit 视为由众多社群组成的网络，而不是传统广播式信息流。内容解释平台术语、subreddit 文化，以及品牌为什么常常高估负面情绪，却低估真实讨论的价值。节目区分了付费广告与自然参与，并分析各自在什么场景下适合品牌。成功运营要先理解相关社群的语言、规范和关注点；即使定向准确，忽略语境的推广内容仍会显得冒犯。讨论还涉及品牌安全、Reddit 上的新兴创作者行为，以及平台对搜索的影响。随着 Reddit 对话越来越多地进入 AI 答案，有价值的参与既能积累社群信誉，也能提升外部发现。核心策略是先研究、再贡献，并把信任视为长期累积的资产。",
    url: "https://goatagency.com/blog/overherd-on-social-reddit/", image: "",
  },
  {
    id: 12, category: "social", subcategory: "Social Media Strategy", platforms: ["TikTok"],
    source: "Social Media Today", date: "July 23, 2026",
    title: "5 tips for building an effective brand presence on TikTok",
    titleZh: "品牌在 TikTok 建立有效影响力的五个建议",
    summary: "A concise research-to-execution loop for TikTok: study trends and top ads, build a format database, map creators, formulate a niche strategy and use analytics to refine it.",
    summaryZh: "一套简明的 TikTok 研究与执行闭环：研究趋势和优秀广告、建立形式数据库、梳理创作者、制定细分策略，再用数据持续优化。",
    digest: "Social Media Today recommends treating TikTok strategy as a research discipline rather than a race to copy the latest viral sound. Marketers can begin with TikTok Trends and the Top Ads library to identify topics, formats and creative patterns by region, sector and objective. Those observations should become a working database of themes and video structures, not a list of trends to reproduce blindly. The next step is creator research: creators often understand platform language better than brands, and reviewing who succeeds inside a specific niche helps teams find both potential partners and native content conventions. The brand can then formulate a strategy around the audience’s interests, questions and recurring formats, while avoiding overt promotion that interrupts the feed. Analytics completes the loop by showing which subjects, structures and voices deserve further investment. The guide’s strongest principle is that TikTok relevance comes from learning how a community behaves and what it wants answered, then adapting the brand’s expertise to that behavior.",
    digestZh: "Social Media Today 建议把 TikTok 策略当作研究工作，而不是竞相复制最新病毒音乐。营销人员可以从 TikTok Trends 和 Top Ads 资料库入手，按地区、行业和目标识别热门主题、内容形式与创意模式。这些观察应被整理成持续更新的主题和视频结构数据库，而不是一份盲目跟随的趋势清单。下一步是研究创作者：他们通常比品牌更熟悉平台语言，分析细分领域中的优秀创作者既能发现合作对象，也能理解原生内容规范。随后，品牌可围绕受众兴趣、问题和重复出现的形式制定策略，避免生硬推广破坏信息流体验。最后通过数据判断哪些主题、结构和声音值得继续投入。文章最重要的原则是：TikTok 相关性来自理解社群行为和需求，再把品牌专长适配进去。",
    url: "https://www.socialmediatoday.com/news/5-tips-for-building-an-effective-brand-presence-on-tiktok/824784/", image: "",
  },
  {
    id: 13, category: "social", subcategory: "Social Media Case Study", platforms: ["Instagram", "TikTok"],
    source: "Marketing Brew", date: "July 23, 2026",
    title: "How yogurt brand Sourmilk is making its mark on- and offline",
    titleZh: "酸奶品牌 Sourmilk 如何在线上线下建立影响力",
    summary: "Sourmilk combines founder-led storytelling, deliberately provocative IRL product drops and separate founder and brand accounts to build demand before expanding retail distribution.",
    summaryZh: "Sourmilk 通过创始人内容、刻意制造话题的线下产品派发，以及相互区分的创始人与品牌账号，在扩大零售铺货前先建立需求。",
    digest: "Sourmilk could not use direct-to-consumer shipping as an easy testing channel because fresh yogurt has a limited shelf life. Instead, its founders built demand before retail by delivering more than 8,000 preordered yogurts around New York and turning the distribution constraint into an intentionally provocative “drug deal” story. Founder Kiki Couchman’s personal Instagram and TikTok accounts show the behind-the-scenes reality of building the company, while the brand account handles product information, feedback and event updates. Her personal audience is more than twice the size of the brand’s following, giving Sourmilk two distinct discovery routes. Offline activations—guerilla grocery drops, fitness-studio pop-ups and collaborations with local food brands—are designed to generate moments worth capturing on social. The strategy also produces practical business intelligence: early-access sign-ups have built an email list of about 5,000 people with ZIP-code data that helps guide retail expansion. Sourmilk’s system demonstrates how founder access, physical proximity and social documentation can work together when a young brand cannot rely on conventional ecommerce growth.",
    digestZh: "由于新鲜酸奶保质期有限，Sourmilk 无法把 DTC 配送当作轻松的市场测试渠道。创始团队因此先在零售铺货前建立需求：他们在纽约配送了超过 8,000 份预订酸奶，并把配送限制包装成刻意制造话题的“街头交易”故事。创始人 Kiki Couchman 的 Instagram 和 TikTok 个人账号展示创业幕后，品牌账号则负责产品信息、反馈与活动通知。她的个人受众规模超过品牌账号两倍，为 Sourmilk 形成两条不同的发现路径。游击式杂货投放、健身工作室快闪和本地食品品牌合作等线下活动，都被设计成适合社交记录的时刻。这套策略还产生实际商业情报：早鸟名单积累约 5,000 名订阅者及邮编数据，帮助决定零售扩张区域。这个案例展示了当年轻品牌无法依赖传统电商增长时，创始人连接、线下接触与社交记录如何协同。",
    url: "https://www.marketingbrew.com/stories/how-yogurt-brand-sourmilk-is-making-its-mark-on-and-offline", image: "",
  },
  {
    id: 14, category: "social", subcategory: "Social Media Case Study", platforms: ["Instagram", "TikTok"],
    source: "The Goat Agency", date: "2026",
    title: "How did poppi build a culture-first influencer strategy that’s reshaping FMCG marketing?",
    titleZh: "poppi 如何打造重塑快消营销的文化优先达人策略？",
    summary: "Poppi’s social system combines founder storytelling, UGC rewards, college ambassadors, long-term creators and culturally aligned partnerships to turn functional soda into a lifestyle identity.",
    summaryZh: "poppi 把创始人叙事、UGC 奖励、校园大使、长期创作者与文化合作结合起来，把功能汽水塑造成生活方式身份。",
    digest: "The case study traces poppi’s growth from a founder-led Shark Tank brand to a culturally visible beverage acquired by PepsiCo for $2 billion. Its social strategy consistently sells a feeling before a functional ingredient claim. Founder Allison Ellsworth documented the company journey, creating a narrative that continued as the packaging and distribution scaled. User-generated content is actively encouraged through community rewards, while the poppi University ambassador program gives students products, events and reasons to create inside their own networks. The brand invests in recurring creator relationships and places them inside experiences such as Coachella houses, making the content feel like access to a cultural moment rather than a one-off sponsorship. Partnerships with Love Island, BÉIS and Bubble extend the same colorful, wellness-meets-fun identity into adjacent interests. Across TikTok and Instagram, humor, trends and recognizable packaging help poppi behave like a participant in culture. The strategy works because creator selection, community mechanics, collaborations and visual identity all reinforce the same promise instead of operating as disconnected campaigns.",
    digestZh: "该案例梳理了 poppi 从创始人主导的 Shark Tank 品牌，成长为被 PepsiCo 以 20 亿美元收购的文化型饮料品牌。其社交策略始终先出售一种感觉，再讲功能成分。创始人 Allison Ellsworth 持续记录公司成长，使品牌在包装与渠道扩张后仍保留统一叙事。品牌通过社群奖励主动鼓励 UGC，poppi University 校园大使计划则为学生提供产品、活动和在自身网络中创作的理由。poppi 投资长期创作者关系，并把他们放进 Coachella 主题住宅等体验中，让内容更像进入文化现场，而不是一次性赞助。与 Love Island、BÉIS 和 Bubble 的合作把同样的彩色、健康又有趣的身份延伸到相邻兴趣。TikTok 与 Instagram 上的幽默、趋势和高识别包装，让品牌像文化参与者。其成功来自创作者、社群机制、合作与视觉身份始终强化同一承诺。",
    url: "https://goatagency.com/blog/poppi-influencer-marketing-strategy/", image: "",
  },
  {
    id: 15, category: "social", subcategory: "Social Media Case Study", platforms: ["Instagram", "TikTok"],
    source: "Marketing Dive", date: "July 27, 2026",
    title: "Canada Goose brings nature’s fringe to lifestyle marketing push",
    titleZh: "Canada Goose 以自然边缘探索者开启生活方式营销",
    summary: "Canada Goose’s “Natural Intelligence” platform uses tornado chasers, mushroom biologists and other field experts to build social content around credible curiosity rather than conventional celebrity influence.",
    summaryZh: "Canada Goose 的“Natural Intelligence”平台邀请龙卷风追逐者、真菌学家等野外专家，以可信的真实好奇心打造社交内容，而不是依赖传统明星影响力。",
    digest: "Canada Goose is broadening its identity beyond extreme-weather outerwear through stories about people who pursue unusual knowledge in nature. The campaign follows field experts on real adventures and distributes the work through Instagram, TikTok and other channels. Choosing specialists gives the brand subject matter that conventional lifestyle influencers cannot easily reproduce, while remaining connected to exploration, performance and the outdoors. “Natural Intelligence” also creates a repeatable editorial platform rather than a single celebrity spot: each new expert can introduce a different environment, question and field of knowledge within the same brand premise. The work is scheduled to continue through 2026 and likely into 2027, giving the team time to build audience recognition and deepen the idea. The case demonstrates how creator strategy becomes stronger when the person’s real expertise supplies both the content and the reason the brand belongs in the story.",
    digestZh: "Canada Goose 通过讲述在自然中追求独特知识的人物故事，把品牌从极端天气羽绒服扩展到更广泛的生活方式领域。活动跟随野外专家展开真实探索，并通过 Instagram、TikTok 等渠道传播。专业人士带来的题材很难被普通生活方式达人复制，同时仍与探索、性能和户外精神保持一致。“Natural Intelligence”也不是单次明星广告，而是可持续的编辑平台：每位新专家都能在同一品牌前提下带来不同环境、问题与知识领域。项目计划贯穿 2026 年，并可能延续至 2027 年，让团队有时间建立认知并深化创意。这个案例说明，当创作者的真实专业能力同时提供内容和品牌入场理由时，创作者策略会更有力量。",
    url: "https://www.marketingdive.com/news/canada-goose-brings-natures-fringe-to-lifestyle-marketing-push/826134/", image: "",
  },
  {
    id: 16, category: "social", subcategory: "Social Media Case Study", platforms: ["Cross-platform"],
    source: "Marketing Dive", date: "July 27, 2026",
    title: "Gap Inc. opens creator program to employees",
    titleZh: "Gap Inc. 向员工开放创作者计划",
    summary: "Gap is inviting corporate, distribution and store employees into its creator program, turning people with first-hand product and customer knowledge into paid, disclosed brand storytellers.",
    summaryZh: "Gap 正邀请总部、配送中心和门店员工加入创作者计划，把真正了解产品与顾客的一线人员转化为获得佣金、清晰披露关系的品牌讲述者。",
    digest: "Gap Inc. expanded its creator program to eligible employees across offices, stores and distribution centers. Participants can promote Gap, Old Navy, Athleta and Banana Republic through social posts, newsletters, product storytelling and creator spotlights while following disclosure and brand-standard guidance. The program launched to external creators last October and has generated almost 30,000 posts reaching nearly 154 million consumers. Employees receive product and commission, giving the company an always-on source of content from people who already understand its merchandise and customers. The move supports a broader effort to rebuild Gap’s cultural relevance: the namesake brand grew first-quarter sales 10% year over year, while recent celebrity and nostalgia-led campaigns kept it in conversation. The case shows how employee advocacy can evolve from informal enthusiasm into structured creator infrastructure with incentives, governance and measurable reach, without erasing the authenticity that made employees credible participants in the first place.",
    digestZh: "Gap Inc. 已把创作者计划扩展至办公室、门店和配送中心的符合条件员工。参与者可以通过社交帖子、新闻邮件、产品故事和创作者专题推广 Gap、Old Navy、Athleta 与 Banana Republic，同时遵守披露与品牌规范。该计划去年 10 月首先面向外部创作者推出，至今已产生近 3 万条内容，触达约 1.54 亿消费者。员工可获得产品与佣金，让公司拥有一批本就了解商品和顾客的长期内容来源。此举也服务于 Gap 重建文化影响力的更大目标：同名品牌第一季度销售同比增长 10%，明星合作和怀旧活动持续带动讨论。这个案例展示员工倡导如何升级为具备激励、治理与可衡量触达的创作者基础设施，同时不抹去员工原本的可信度。",
    url: "https://www.marketingdive.com/news/gap-inc-opens-creator-influencer-program-staff-employees/826275/", image: "",
  },
  {
    id: 9, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Dive", date: "July 27, 2026",
    title: "Rare Beauty draws inspiration from Greek mythology for global campaign",
    titleZh: "Rare Beauty 全球活动从希腊神话汲取灵感",
    summary: "Rare Beauty built a global creative platform around Greek mythology, using an established cultural story world to give its beauty launch a recognizable and expandable narrative.",
    summaryZh: "Rare Beauty 围绕希腊神话建立全球创意平台，借助大众熟悉的文化故事，为美妆新品打造易识别、可延展的叙事。",
    digest: "The campaign uses Greek mythology as the organizing idea for a global beauty story rather than treating individual product assets as disconnected launches. A shared narrative gives the brand visual consistency across markets while leaving room for characters, symbols and content formats to evolve. The approach shows how an emerging global brand can borrow cultural familiarity while still expressing its own tone and product message.",
    digestZh: "该活动把希腊神话作为全球美妆故事的核心结构，而不是把不同产品素材做成互不相关的发布。共同叙事既能让品牌在不同市场保持视觉一致，也为角色、符号和内容形式留下延展空间。这说明成长中的全球品牌可以借助大众熟悉的文化，同时仍保留自己的语气与产品信息。",
    url: "https://www.marketingdive.com/news/rare-beauty-draws-inspiration-from-greek-mythology-for-global-campaign/826225/", image: "",
  },
  {
    id: 10, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Dive", date: "July 27, 2026",
    title: "Under Armour teams with ‘Heated Rivalry’ star for new campaign",
    titleZh: "Under Armour 携手《Heated Rivalry》演员推出新活动",
    summary: "Under Armour appointed actor François Arnaud as a global ambassador, connecting entertainment fandom with the brand’s performance positioning in a new campaign.",
    summaryZh: "Under Armour 邀请演员 François Arnaud 担任全球品牌大使，在新活动中把娱乐粉丝文化与品牌的运动性能定位连接起来。",
    digest: "The partnership brings a current entertainment figure into Under Armour’s global marketing while keeping the work anchored in performance and personal drive. It is designed to extend beyond a single endorsement through campaign storytelling and ambassador content. The move illustrates how a sports brand can access a new cultural audience without abandoning the product and mindset associations that make the brand credible.",
    digestZh: "这项合作把当下具有关注度的娱乐人物带入 Under Armour 的全球营销，同时仍以运动表现和个人驱动力为核心。合作不只是一次代言，而是通过活动叙事和大使内容持续展开。它展示了运动品牌如何进入新的文化受众，同时不放弃让品牌保持可信度的产品与精神联想。",
    url: "https://www.marketingdive.com/news/under-armour-heated-rivalry-francois-arnaud-global-ambassador/826165/", image: "",
  },
  {
    id: 11, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Dive", date: "July 27, 2026",
    title: "Oscar Mayer fetes Wienermobile’s 90 years with Milk Bar hot dog cake",
    titleZh: "Oscar Mayer 用 Milk Bar 热狗蛋糕庆祝 Wienermobile 90 周年",
    summary: "A limited edible collaboration gives Oscar Mayer’s long-running Wienermobile asset a contemporary social hook and a reason for a new generation to participate.",
    summaryZh: "这项限量食品合作为 Oscar Mayer 历史悠久的 Wienermobile 资产加入当代社交话题，也为新一代消费者提供参与理由。",
    digest: "Oscar Mayer avoided treating a 90th anniversary as a retrospective. Instead, it paired a famous brand asset with Milk Bar and an emerging search behavior to create something new, limited and shareable. The resulting hot-dog cake turns heritage into participation: consumers can buy, photograph and talk about the anniversary rather than only watch a commemorative ad.",
    digestZh: "Oscar Mayer 没有把 90 周年只做成历史回顾，而是把著名品牌资产、Milk Bar 和正在增长的搜索行为结合起来，创造出新鲜、限量且适合分享的产品。热狗蛋糕把品牌历史变成了参与体验：消费者可以购买、拍摄并讨论周年活动，而不只是观看一支纪念广告。",
    url: "https://www.marketingdive.com/news/oscar-mayer-fetes-wienermobiles-90-years-with-milk-bar-hot-dog-cake/826194/", image: "",
  },
  {
    id: 17, category: "ai", subcategory: "AI marketing tools",
    source: "MarketingTech News", date: "July 2026",
    title: "AI try-on linked to higher ecommerce conversion",
    titleZh: "AI 虚拟试穿与更高电商转化率相关",
    summary: "DRESSX research covering 1.2 million fashion shoppers connects virtual try-on use with stronger product exploration, cart activity, retention and purchase conversion.",
    summaryZh: "DRESSX 对 120 万名时尚消费者的研究显示，使用虚拟试穿与更深入的商品浏览、更高加购率、留存率和购买转化有关。",
    digest: "The study treats AI try-on as a commercial experience rather than a decorative product-page feature. Across fashion ecommerce, shoppers who used the tool were more likely to explore additional products, return after their first visit, add an item to cart and complete a purchase. DRESSX reports that try-on users were roughly three times more likely to move from product view to cart and achieved 50% higher purchase conversion overall; the difference was larger for higher-priced fashion, where uncertainty can stop a sale. The findings suggest that visualization can reduce the confidence gap between seeing clothing on a model and imagining it on one’s own body. For marketers, this shifts AI try-on from a novelty asset toward a measurable customer-journey touchpoint that can influence merchandising, content and conversion optimization. The research is vendor-produced, so teams should validate results with their own traffic, product mix, returns and incremental-conversion testing before projecting the same lift.",
    digestZh: "这项研究把 AI 试穿视为商业体验，而不是商品页上的装饰功能。在时尚电商中，使用该工具的消费者更愿意浏览其他商品、首次访问后再次回来、把商品加入购物车并完成购买。DRESSX 表示，试穿用户从商品浏览进入购物车的概率约为普通用户的三倍，整体购买转化高出 50%；在高价时尚商品中差距更明显，因为购买不确定性更高。这说明可视化体验能够缩小“看到模特穿着”与“想象自己穿着”之间的信心缺口。对营销人员而言，AI 试穿因此从新奇功能转变为可衡量的顾客旅程触点，并可能影响商品展示、内容与转化优化。由于研究由供应商发布，品牌仍应结合自身流量、商品结构、退货率与增量测试验证效果。",
    url: "https://www.marketingtechnews.net/news/ai-try-on-ecommerce-conversion-dressx-study/", image: "",
  },
  {
    id: 18, category: "ai", subcategory: "AI marketing tools",
    source: "MarketingTech News", date: "March 6, 2026",
    title: "Coca-Cola expands AI use in marketing and product development",
    titleZh: "可口可乐扩大 AI 在营销与产品开发中的应用",
    summary: "Coca-Cola is moving AI from isolated creative experiments into consumer analysis, campaign adaptation, demand creation and early product ideation across its global system.",
    summaryZh: "可口可乐正把 AI 从孤立的创意实验扩展到消费者分析、活动本地化、需求创造以及全球体系中的早期产品构思。",
    digest: "Coca-Cola is integrating AI more deeply into the way marketing work is planned and executed. Systems can analyze consumer behavior, test variations of content and help local teams adapt global campaigns to market conditions. Digital sales information from retailers and bottling partners can also shorten the feedback loop between promotion, consumer response and the next decision. The use case reaches beyond communications: Coca-Cola Y3000 Zero Sugar used AI-supported analysis of how people imagined the “taste of the future” to inform flavor and packaging development. That example illustrates how marketing intelligence can move upstream into product ideation rather than arriving only after a product has been created. The company still positions human teams as owners of brand identity, judgment and the final message. The meaningful change is speed—large volumes of consumer signals and creative possibilities can be examined more quickly across markets. For marketers, the case is valuable because AI is being treated as shared operating infrastructure connecting insight, product and campaign work, not simply as a faster image or copy generator.",
    digestZh: "可口可乐正把 AI 更深入地整合进营销规划与执行。系统可以分析消费者行为、测试不同内容，并帮助本地团队根据市场情况调整全球活动。来自零售商和装瓶合作伙伴的数字销售数据，也能缩短促销、消费者反馈与下一步决策之间的周期。应用还延伸到传播之前：Coca-Cola Y3000 Zero Sugar 曾借助 AI 分析消费者如何想象“未来的味道”，并把洞察用于风味与包装开发。这说明营销情报可以进入产品构思上游，而不只在产品完成后发挥作用。公司仍把品牌身份、判断和最终信息交由人工团队负责。真正的变化在于速度——品牌可以更快地跨市场分析大量消费者信号与创意可能。这个案例的价值在于，AI 被视为连接洞察、产品和活动工作的共同基础设施，而不只是更快的图像或文案生成器。",
    url: "https://www.marketingtechnews.net/news/coca-cola-expands-ai-use-in-marketing-and-product-development/", image: "",
  },
  {
    id: 19, category: "ai", subcategory: "AI marketing tools",
    source: "MarketingTech News", date: "February 10, 2026",
    title: "Reddit and AI search are reshaping how brands get found",
    titleZh: "Reddit 与 AI 搜索正在重塑品牌被发现的方式",
    summary: "Community conversations increasingly influence both conventional search results and AI-generated recommendations, making authentic Reddit participation relevant to brand discovery.",
    summaryZh: "社群对话正越来越多地影响传统搜索结果和 AI 生成的推荐，使品牌在 Reddit 上的真实参与成为新的发现渠道。",
    digest: "The article connects two discovery behaviors that marketers often manage separately: community participation and AI search visibility. Reddit threads frequently rank in conventional search and are also cited by AI systems, extending the useful life of an authentic discussion beyond the platform feed. That creates an opportunity, but not one that behaves like conventional advertising. Reddit communities tend to reject promotional messages that ignore their rules, language and existing conversations. Brands therefore need to contribute information that is genuinely helpful before expecting visibility or recommendation value. The article also describes the emerging practice of optimizing authoritative information so language models can interpret and cite a brand accurately. In this environment, success is less about winning a single click and more about becoming a credible answer across community, search and AI interfaces. Marketers should treat claims from specialist providers cautiously, but the underlying operating lesson is strong: social, SEO, public information and reputation can no longer be planned as isolated channels when the same discussion may influence people and machines for months.",
    digestZh: "文章把营销人员常常分开管理的两种发现行为连接起来：社群参与和 AI 搜索可见度。Reddit 讨论经常出现在传统搜索结果中，也会被 AI 系统引用，使一段真实、有用的对话在离开信息流后仍能持续产生影响。但这种机会并不像传统广告。Reddit 社群往往排斥忽略规则、语言和既有对话的推广内容，因此品牌必须先贡献真正有帮助的信息，再期待获得曝光或推荐。文章还介绍了新兴的 AI 搜索优化实践：通过权威信息帮助语言模型准确理解并引用品牌。在这种环境中，成功不只是赢得一次点击，而是成为社群、搜索与 AI 界面中的可信答案。虽然营销人员应谨慎看待服务商自己的效果数据，但核心运营启示成立：当同一讨论可能持续数月影响人和机器时，社交、SEO、公开信息与声誉不能继续被当作孤立渠道。",
    url: "https://www.marketingtechnews.net/news/reddit-and-ai-search-are-reshaping-how-brands-get-found/", image: "",
  },
  {
    id: 20, category: "ai", subcategory: "Ad tech",
    source: "MarketingTech News", date: "July 22, 2026",
    title: "ChatGPT ads test a new model for conversational advertising",
    titleZh: "ChatGPT 广告正在测试一种新的对话式广告模式",
    summary: "ChatGPT Ads matches placements to conversational context and intent rather than a fixed keyword list, creating new questions about targeting control, measurement and user experience.",
    summaryZh: "ChatGPT 广告根据对话语境与意图匹配内容，而不是依赖固定关键词，因此带来关于定向控制、衡量与用户体验的新问题。",
    digest: "OpenAI’s advertising test is developing into a distinct buying environment. Advertisers can use self-service campaign management, cost-per-click bidding, conversion tracking, location targeting, budgets and pacing, but they receive fewer controls and less reporting detail than on Google or Meta. Instead of selecting exact keywords, a brand supplies contextual hints describing the conversations, needs or situations in which its product may be relevant. ChatGPT then evaluates the current exchange, the advertisement, its landing page and advertiser information before deciding whether to show it. This could place a brand closer to a consumer’s comparison or decision process, but it also makes the matching logic less transparent. Limited inventory and reporting mean marketers cannot yet assume mature-channel scale or optimization. The practical opportunity is a disciplined test: define which conversational situations matter, create landing experiences aligned with those needs and measure incremental outcomes carefully. The format is important because it changes advertising from interrupting content toward entering an active dialogue, while raising higher expectations for relevance, privacy and restraint.",
    digestZh: "OpenAI 的广告测试正在形成一种独特的购买环境。广告主可以使用自助管理、按点击出价、转化追踪、地理定向、预算和节奏控制，但与 Google 或 Meta 相比，控制项与报告细节仍更少。品牌不再选择精确关键词，而是提供“语境提示”，描述产品适合出现的对话、需求或情境。ChatGPT 会结合当前交流、广告内容、落地页和广告主信息决定是否展示。这可能让品牌更接近消费者的比较与决策过程，但匹配逻辑也更不透明。库存和报告限制意味着营销人员不能假设它已经具备成熟渠道的规模与优化能力。更实际的做法是进行有纪律的测试：明确重要对话场景、设计与需求一致的落地体验，并仔细衡量增量结果。这一形式的重要性在于，广告从打断内容转向进入正在发生的对话，同时对相关性、隐私与克制提出更高要求。",
    url: "https://www.marketingtechnews.net/news/chatgpt-ads-conversational-advertising/", image: "",
  },
  {
    id: 21, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Brew", date: "July 24, 2026",
    title: "Inside Nike’s ‘Rip the Script’ World Cup campaign",
    titleZh: "走进 Nike“Rip the Script”世界杯营销活动幕后",
    summary: "Nike built a World Cup ecosystem around an athlete-led hero film, then expanded access through creators and partners to generate three billion views across platforms.",
    summaryZh: "Nike 以运动员主导的主影片为核心建立世界杯传播生态，再通过创作者和合作伙伴扩展入口，在各平台获得 30 亿次观看。",
    digest: "Nike’s World Cup effort began with a six-minute hero film featuring more than 30 athletes and actors moving through television and film sets. The production required 42 days, multiple cities, crews and schedules built around athletes competing at the highest level. Yet the campaign’s reach did not depend on the film alone. Nike designed an ecosystem of athletes, creators and creative partners that offered different audiences an entry into the same football narrative. The company reports three billion total views: more than 1.2 billion through owned channels, 1.6 billion from creator content and 400 million through athlete and creative partners. The film itself celebrates instinctive play and allowed room for athlete improvisation, even inside an unusually complex production. That tension is the central lesson: disciplined coordination created the conditions for spontaneity instead of scripting away the people who made the idea credible. Nike is also treating the tournament as a starting point, using renewed football interest to support participation and future events rather than letting attention end with the final match.",
    digestZh: "Nike 的世界杯活动以一支六分钟主影片开始，超过 30 位运动员与演员在不同电视和电影场景中穿梭。制作历时 42 天，涉及多个城市、团队，并需配合正在参加顶级赛事的球员行程。但活动影响力并不只依赖这支影片。Nike 建立了由运动员、创作者和创意伙伴组成的传播生态，让不同受众都能进入同一个足球叙事。公司称总观看量达到 30 亿：自有渠道超过 12 亿、创作者内容 16 亿、运动员与创意伙伴约 4 亿。影片强调本能与创造性踢法，即使制作复杂，仍允许运动员即兴发挥。核心启示正在这种张力中：严密协调的目的不是抹去人物，而是为真实自发表现创造条件。Nike 也把世界杯视为起点，希望把赛事激发的兴趣转化为持续参与，并连接未来足球赛事。",
    url: "https://www.marketingbrew.com/stories/nike-rip-the-script-world-cup-campaign", image: "",
  },
  {
    id: 22, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Brew", date: "July 21, 2026",
    title: "Hilary Duff, ‘Cash Cab,’ and branded newspapers: How Ladder is communicating ‘stronger, not smaller’ to women",
    titleZh: "Hilary Duff、《Cash Cab》与品牌报纸：Ladder 如何向女性传达“更强，而不是更瘦”",
    summary: "Ladder challenges weight-training misinformation with an optimistic platform spanning Hilary Duff films, “Strong Girl Summer” print and an educational quiz-cab activation.",
    summaryZh: "Ladder 以积极的品牌平台反击力量训练误解，内容覆盖 Hilary Duff 影片、“Strong Girl Summer”印刷物和知识问答出租车互动。",
    digest: "Ladder’s campaign responds to a specific tension among its audience: roughly 80% to 85% of its 400,000 members are women, yet fear of becoming bulky and the return of “thin is in” messaging can discourage strength training. “Stronger, not smaller” replaces a restrictive body ideal with a promise based on capability. Hilary Duff provides cultural recognition across millennials and younger TikTok audiences, appearing in a hero film and a mock corporate-compliance video that challenges common myths. The platform then moves beyond celebrity advertising. During Miami Swim Week, Ladder distributed branded zines and outdoor messages announcing “Strong Girl Summer.” A “Ladder Quiz Cab” activation with Ben Bailey turned strength-training education into entertainment and rewarded correct answers. These executions vary in format but serve the same strategic job: make misinformation discussable, approachable and fun. The campaign works because the message reflects the actual composition and concerns of Ladder’s membership rather than borrowing a generic empowerment line. Its optimistic emotional contract gives the brand a clear enemy—limiting beliefs—without shaming the people it wants to support.",
    digestZh: "Ladder 的活动回应了核心受众的真实矛盾：其 40 万名会员中约 80% 至 85% 是女性，但对力量训练会让身体“过于壮硕”的担忧，以及“越瘦越好”信息的回潮，可能阻止她们开始训练。“更强，而不是更瘦”用身体能力替代限制性的外形理想。Hilary Duff 同时连接千禧一代和年轻 TikTok 受众，出演主影片与模仿企业合规培训的长视频，拆解常见误解。活动还超越明星广告：Miami Swim Week 期间，品牌以户外广告和小报推广“Strong Girl Summer”；与 Ben Bailey 合作的“Ladder Quiz Cab”则把力量训练知识变成娱乐问答并设置奖金。不同形式服务于同一任务：让误解更容易被讨论、理解和纠正。活动有效，是因为信息来自会员结构与真实顾虑，而不是借用空泛的女性赋能口号。品牌把“限制性观念”设为对手，却没有羞辱需要帮助的人。",
    url: "https://www.marketingbrew.com/stories/hilary-duff-cash-cab-and-branded-newspapers-how-ladder-is-communicating-stronger-not-smaller-to-women", image: "",
  },
  {
    id: 23, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Brew", date: "July 13, 2026",
    title: "Behind the scenes of The Gist’s first brand campaign",
    titleZh: "The Gist 首次品牌活动幕后",
    summary: "The sports media company uses the World Cup to challenge exclusionary fan culture with an ironic academy where every kind of supporter belongs.",
    summaryZh: "这家体育媒体公司借世界杯挑战排外的球迷文化，以一所充满反讽意味、欢迎各种球迷的学院作为创意世界。",
    digest: "The Gist’s first brand campaign, “Fandom Belongs to Everyone,” uses World Cup attention to address people who love sports but have not always felt welcomed by sports culture. The company covers men’s and women’s sports equally and wants to challenge the assumption that the default fan is male. Its film presents The Gist as an elite sports academy, then overturns the exclusivity associated with that setting by introducing alumni who represent many fan archetypes—from statistics experts to people devoted to chronically disappointing teams. The concept gives casual and newly initiated fans a way to recognize themselves without dismissing die-hard knowledge. Social edits focus on different characters, allowing the campaign to extend across the tournament rather than rely on one film. The Gist is measuring social growth, newsletter subscriptions, engagement, shares and reposts, with relatable comments serving as an early signal that audiences feel represented. Branded jerseys make the inclusive promise collectible and give the platform a physical expression. The campaign connects a timely cultural moment to the company’s longer-standing positioning instead of manufacturing an unrelated World Cup stunt.",
    digestZh: "The Gist 的首个品牌活动“Fandom Belongs to Everyone”借世界杯关注度，回应那些热爱体育、却未必被体育文化欢迎的人。公司一直平等报道男女体育，并希望挑战“典型球迷默认是男性”的假设。影片把 The Gist 设定为精英体育学院，再通过不同校友角色颠覆学院象征的排他性：既有熟悉每项数据的资深球迷，也有忠诚支持表现不佳球队的人。这一概念让休闲观众和新球迷都能看到自己，同时不贬低专业知识。社交剪辑分别突出不同人物，使活动能在赛事期间持续展开，而不只依赖一支影片。团队通过社交增长、新闻邮件订阅、互动、分享与转发衡量效果；观众留言表示“被看见”，成为早期正面信号。品牌球衣则把包容承诺变成可收藏的实体表达。活动把及时的文化事件连接到公司长期定位，而不是制造无关的世界杯噱头。",
    url: "https://www.marketingbrew.com/stories/the-gists-brand-campaign-world-cup", image: "",
  },
  {
    id: 24, category: "brand", subcategory: "D2C highlight",
    source: "Marketing Dive", date: "July 20, 2026",
    title: "Purely Elizabeth lampoons protein-maxxing for major product launch",
    titleZh: "Purely Elizabeth 以幽默讽刺“蛋白质极大化”热潮，推出重要新品",
    summary: "The challenger granola brand uses category satire, creator commerce and live sports media to launch a natural-ingredient protein line while pursuing $300 million in annual sales.",
    summaryZh: "这家挑战者格兰诺拉品牌结合品类讽刺、创作者电商与体育媒体，推广天然原料蛋白产品，并向 3 亿美元年销售目标迈进。",
    digest: "Purely Elizabeth is entering the crowded protein category without imitating its most aggressive performance language. “Protein Product Madness” jokes about protein-maxxing through exaggerated products such as protein candy, wine and toothpaste, then contrasts that behavior with granola made from nuts, seeds and oats rather than isolates and fillers. The national campaign is the brand’s largest media investment behind a product launch and spans US Open broadcasts, streaming, paid social, programmatic media and a Columbus Circle station takeover. A frozen-yogurt truck, product seeding, TikTok Shop affiliates and creators extend the launch into experience and commerce. The channel choices reflect a younger audience: TikTok has helped the brand reach Gen Z, while live sports offers concentrated attention in a fragmented media environment. The business context makes the campaign more significant. Purely Elizabeth doubled in two years, reached $200 million in 2025 sales and is targeting $300 million in 2026. The company frames itself as a modern wellness lifestyle brand, using personality and cultural critique to differentiate a functional product rather than relying on a higher protein number alone.",
    digestZh: "Purely Elizabeth 进入拥挤的蛋白质品类时，没有模仿最激进的健身表现话术。“Protein Product Madness”通过蛋白糖果、蛋白酒甚至蛋白牙膏等夸张例子，讽刺“凡物皆要加蛋白”的热潮，再突出产品以坚果、种子和燕麦提供蛋白，而不是加入分离物与填充剂。这是品牌迄今为新品投入最大的全国媒体活动，覆盖美网转播、流媒体、付费社交、程序化广告和纽约 Columbus Circle 地铁站。冻酸奶餐车、产品寄送、TikTok Shop 联盟与创作者把发布延伸到体验和电商。渠道选择与年轻受众一致：TikTok 帮助品牌触达 Z 世代，体育直播则在媒体碎片化环境中提供集中注意力。业务背景让活动更值得关注：Purely Elizabeth 两年内规模翻倍，2025 年销售额达到 2 亿美元，2026 年目标为 3 亿美元。品牌把自己定义为现代健康生活方式品牌，用个性与文化观察区分功能产品，而不是只比较蛋白质数字。",
    url: "https://www.marketingdive.com/news/purely-elizabeth-lampoons-protein-maxxing-for-major-product-launch/825554/", image: "",
  },
  {
    id: 25, category: "brand", subcategory: "D2C highlight",
    source: "Marketing Dive", date: "July 21, 2026",
    title: "How Dum Dums owner Spangler created a candy empire built on nostalgia",
    titleZh: "Dum Dums 母公司 Spangler 如何以怀旧打造糖果帝国",
    summary: "Spangler grows a portfolio of century-old candy brands by acquiring distressed assets, restoring the right heritage cues and changing only what improves contemporary relevance.",
    summaryZh: "Spangler 通过收购经营困难的老品牌、恢复关键传统资产，并只调整真正影响当代相关性的部分，发展百年糖果组合。",
    digest: "Spangler has built a defensible candy portfolio around brand histories competitors cannot reproduce quickly. Rather than inventing most of its major products, the fourth-generation family business acquires legacy assets—often from financial distress—and decides carefully what should be restored, refreshed or left alone. Bit-O-Honey received more adult packaging, a less juvenile mascot and a return to its softer original recipe with more almonds; sales rose 50% in the following year. Sweethearts restored its classic flavors and crunch while adding topical conversation-heart messages such as “Love in This Economy,” allowing an old product to join current dating and cost-of-living conversations. In contrast, Spangler left Necco wafe…2438 tokens truncated…chmarks and produced nearly 1.5 billion press and social impressions. Gap recorded its tenth consecutive quarter of positive comparable sales, with Q1 2026 comps rising 10%. The strategic question is whether repeatedly referencing the 1990s builds a coherent, ownable platform or eventually narrows the brand’s future. For now, the work demonstrates how a company can reactivate established brand codes, attach them to contemporary talent and connect campaign attention directly to a core commercial category rather than using nostalgia as decoration alone.",
    digestZh: "Gap 的“Hailey Jean”胶囊系列与活动再次启用品牌在 1990 年代巅峰时期的视觉语言。极简场景、录音机、显像管电视、有线电话和笨重电脑共同指向 1996 年，而 Hailey Bieber 则为这段历史加入当代时尚相关性。系列在线上及北美和部分国际门店销售。这并非孤立的怀旧尝试，而是 Gap 近期把牛仔、音乐与文化人物结合的延续。2025 年与 Katseye 合作的“Better in Denim”获得超过 80 亿次曝光和 5 亿次观看，并推动牛仔品类实现双位数增长；与 Young Miko 的春季活动也超出目标，获得近 15 亿次媒体与社交曝光。Gap 已连续十个季度实现同店销售增长，2026 年第一季度增长 10%。真正的策略问题是：持续引用 90 年代能否形成品牌独有、可延展的平台，还是最终限制品牌未来。就目前而言，这项工作说明品牌可以重新激活既有符号，把它们连接到当代人物和核心商业品类，而不是只把怀旧当作装饰。",
    url: "https://www.marketingdive.com/news/gap-sticks-with-90s-nostalgia-denim-for-hailey-bieber-capsule-campaign/825378/", image: "",
  },
  {
    id: 29, category: "ai", subcategory: "AI marketing tools",
    source: "MarketingTech News", date: "July 28, 2026",
    title: "Michaels says AI shopping assistant more than doubles conversions",
    titleZh: "Michaels 称 AI 购物助手令转化率提升至传统搜索的两倍以上",
    summary: "Michaels’ Gemini-powered Ask Mike turns broad creative intentions into guided product discovery, and early use is converting at more than twice the rate of conventional site search.",
    summaryZh: "Michaels 的 Gemini 购物助手 Ask Mike 把模糊的创作意图转化为引导式商品发现，早期使用者的转化率超过传统站内搜索的两倍。",
    digest: "Michaels has moved conversational AI from a service experiment into the shopping journey with Ask Mike, an assistant built on Google Cloud’s Gemini Enterprise for Customer Experience. Instead of requiring shoppers to know an exact product name, it can respond to project-led prompts such as planning a child’s birthday party, choosing supplies for DIY curtains or finding a frame for a holiday photo. The assistant asks follow-up questions about materials, colours, budgets and project needs, then guides users toward relevant products. Michaels says the tool was built in six weeks and has handled roughly 75,000 interactions since going live in May. The most important early signal is commercial: users engaging with Ask Mike are converting at more than twice the rate of shoppers using traditional site search. That result suggests conversational commerce is most useful when it solves a category-specific discovery problem rather than simply placing a generic chatbot beside the search bar. Arts and crafts purchases often begin with an outcome or inspiration, while retail catalogues are organised by individual items. Ask Mike attempts to bridge that gap. The article is still an early-stage case, and Michaels has not disclosed enough detail to prove incrementality, long-term retention or the assistant’s effect on basket size. Even so, it gives marketers a concrete implementation pattern: start with high-intent, poorly structured customer questions; connect the assistant to real catalogue data; and judge it by behaviour and conversion rather than conversation volume alone.",
    digestZh: "Michaels 通过 Ask Mike 把对话式 AI 从客服实验带入购物旅程。该助手基于 Google Cloud 的 Gemini Enterprise for Customer Experience 构建，不要求消费者先知道准确商品名称，而是能够回应“为孩子策划生日派对”“为自制窗帘选择材料”或“给旅行照片找相框”等以项目为起点的问题。它会继续询问材料、颜色、预算和具体需求，再把用户引导到相关商品。Michaels 表示，该工具在六周内完成开发，自五月上线以来已处理约 7.5 万次互动。最值得关注的是商业结果：使用 Ask Mike 的消费者，其转化率超过传统站内搜索用户的两倍。这说明，对话式商业真正有价值的场景，不是在搜索框旁边简单增加通用聊天机器人，而是解决某个品类特有的发现难题。手工与创意消费往往从一个目标或灵感开始，但零售目录通常按单件商品组织，Ask Mike 正试图连接这两者。案例仍处早期，Michaels 尚未披露足够数据来证明增量效果、长期留存或客单价影响。不过，它已提供清晰的实施路径：先找到高意图但表达不够结构化的消费者问题，把助手接入真实商品数据，并用行为与转化而不是对话数量来判断成效。",
    url: "https://www.marketingtechnews.net/news/michaels-ai-shopping-assistant-conversions/", image: "",
  },
  {
    id: 30, category: "social", subcategory: "Social Media Case Study", platforms: ["TikTok", "Instagram"],
    source: "Marketing Brew", date: "April 1, 2026",
    title: "How InStyle is reaching the next gen with its original social series",
    titleZh: "InStyle 如何通过原创社交连续剧触达新一代受众",
    summary: "InStyle’s mockumentary franchises make entertainment—not referral traffic—the first objective, building younger reach and a sponsor-ready format that works as standalone episodes.",
    summaryZh: "InStyle 的伪纪录片系列把娱乐而非导流设为首要目标，以可独立观看的剧集扩大年轻受众，并形成可承载赞助的内容资产。",
    digest: "InStyle is treating social video as original programming rather than a promotional cut-down of magazine content. Its workplace mockumentary The Intern has produced more than 40 episodes across eight seasons and generated over 36 million views in its first year. A newer companion series, The Boss, reached 2.3 million views soon after launch. Both are designed to entertain first, not drive immediate website traffic, helping a legacy media brand become relevant to Gen Z and Gen Alpha audiences who may discover InStyle through a recurring show rather than a print title. The format combines real InStyle employees, improvisational comedy and rotating creators or celebrities. Episodes are connected by recurring characters and office dynamics, but each is written to work independently because social algorithms rarely deliver a series in chronological order. That design principle is especially useful for marketers: continuity can build familiarity without making a new viewer feel late to the story. InStyle has also turned the audience into a commercial product. Fossil and e.l.f. Cosmetics have appeared in episodes, new concepts have secured sponsors before launch, and parent company People Inc. reported year-over-year growth in digital and advertising revenue. The editorial team is transparent about integrations and makes them part of the fictional world rather than disguising them. The case shows how a brand can build an owned entertainment format that supports discovery, repeat viewing and sponsorship simultaneously. Its strategic discipline is to protect the show’s entertainment value first; monetisation follows only when the partnership behaves naturally inside the established format.",
    digestZh: "InStyle 正把社交视频当作原创节目，而不是杂志内容的宣传剪辑。其职场伪纪录片《The Intern》在第一年推出八季、超过 40 集，累计观看量超过 3600 万；新系列《The Boss》上线不久也获得 230 万次观看。两者都把娱乐放在首位，而不是追求即时网站流量，使这个传统媒体品牌能够触达通过连续短剧而非纸质杂志认识 InStyle 的 Z 世代与 Alpha 世代。内容结合真实员工、即兴喜剧以及轮换出现的创作者和名人。剧集通过固定角色与办公室关系保持连续性，但每一集都能独立观看，因为社交算法不会按顺序分发内容。这一点对营销人员尤其重要：连续性可以累积熟悉感，却不会让新观众觉得自己错过了前情。InStyle 也把受众转化为商业资产。Fossil 与 e.l.f. Cosmetics 已进入部分剧集，新的节目概念在上线前就获得赞助；母公司 People Inc. 的数字与广告收入也实现同比增长。团队会明确说明商业合作，并让产品自然进入虚构世界，而不是试图隐藏植入。这个案例说明，品牌可以建立同时服务于发现、重复观看和赞助的自有娱乐形式。其核心纪律是先保护节目的娱乐价值，只有当合作能自然存在于既定内容世界中时，商业化才会成立。",
    url: "https://www.marketingbrew.com/stories/2026/04/01/instyle-original-social-series", image: "",
  },
  {
    id: 31, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Dive", date: "July 17, 2026",
    title: "Campaign Trail: Yeti spells out consumer passions with four-letter words",
    titleZh: "Campaign Trail：Yeti 用四字母单词表达消费者热爱",
    summary: "Yeti turns its four-letter block logo into a flexible language for consumer passions, extending the brand beyond hunting and fishing without abandoning its minimalist identity.",
    summaryZh: "Yeti 把四字母块状标识变成表达消费者热爱的灵活语言，在不放弃极简品牌个性的前提下突破狩猎与钓鱼的传统边界。",
    digest: "Yeti’s “Four Letters” platform expands the outdoor brand by transforming its most recognisable asset: the four-letter, block-type logo. Developed with Wieden + Kennedy Portland, the idea replaces Yeti with concise words connected to passions, pursuits and commitment. A 60-second anthem uses found and ambassador-shot footage, a metronomic soundtrack and pairings such as “game” and “time” or “duck” and “dive.” A skateboard sequence moves through “fail,” “bail,” “quit” and “nope,” creating a miniature story without voiceover. The approach grows from Yeti’s internal “bull-simple” product philosophy—remove anything unnecessary and retain only what helps people pursue what they love. Strategically, the platform broadens the audience beyond hunting and fishing without inventing a new brand purpose. Yeti becomes an enabler for people who are intensely committed to almost any activity. The system extends across ambassador films, outdoor media around major sporting events, retail and limited-edition stickers. It has already adapted to cultural moments, including a Fourth of July Instagram execution using words such as “beer,” “dogs,” “hang” and “time.” The strength is not one clever advertisement but a repeatable creative grammar: the logo, language and audience’s own passions can generate many executions while remaining instantly recognisable. For marketers, the case demonstrates a disciplined route to brand expansion. Instead of stretching into generic lifestyle territory, identify a distinctive asset, connect it to a broader human motivation and create rules simple enough that audiences and local teams can participate without weakening the central idea.",
    digestZh: "Yeti 的“Four Letters”品牌平台通过改造最具辨识度的资产——四字母块状标识——来扩大户外品牌的边界。该创意由 Wieden + Kennedy Portland 参与打造，以表达热爱、追求与投入的简短单词替换 Yeti。60 秒主片采用真实素材和品牌大使拍摄画面，以节拍器般的音乐串联“game/time”“duck/dive”等词组；滑板段落则用“fail、bail、quit、nope”在没有旁白的情况下讲出一个微型故事。这种表达延续了 Yeti 内部的“bull-simple”产品哲学：去掉不必要的部分，只保留帮助人们坚持热爱所需的内容。策略上，它让品牌超越狩猎和钓鱼，却没有凭空创造新的品牌使命；Yeti 被定义为任何高度投入者的支持者。该系统可以延展到品牌大使短片、大型赛事周边户外广告、零售和限量贴纸，也已用于美国独立日的 Instagram 内容，以“beer、dogs、hang、time”等词回应当下文化。它的价值不只是一条聪明广告，而是一套可重复的创意语法：标识、文字和受众自己的热爱能够持续生成新内容，同时保持即时识别。对营销人员而言，这是品牌扩张的克制路径——找到独特资产，把它连接到更广泛的人类动机，再制定足够简单的规则，让消费者与本地团队参与而不削弱核心创意。",
    url: "https://www.marketingdive.com/news/campaign-trail-yeti-spells-out-consumer-passions-with-four-letter-words/825390/", image: "",
  },
  {
    id: 32, category: "ai", subcategory: "AI marketing tools",
    source: "MarketingTech News", date: "March 10, 2026",
    title: "Target uses AI to predict retail trends and speed up product decisions",
    titleZh: "Target 利用 AI 预测零售趋势并加快产品决策",
    summary: "Target’s Trend Brain combines fashion-image analysis with social sentiment to identify emerging demand earlier, helping design, merchandising and campaign teams move almost twice as fast.",
    summaryZh: "Target 的 Trend Brain 结合时尚图像分析与社交情绪，提前识别新兴需求，使设计、商品与营销团队的行动速度接近过去的两倍。",
    digest: "Target is applying AI upstream of advertising, where product and merchandising decisions determine what marketing will eventually have to sell. Its internal Trend Brain platform analyses fashion imagery alongside social-media sentiment to predict which apparel styles may gain momentum in the next season. The system gives designers a faster way to assemble new concepts and helps teams rotate collections almost twice as quickly as before. It can also flag potential underperformance early. Target cited polka dots as one example: an emerging signal allowed the retailer to increase its commitment before the trend became obvious. The marketing value comes from connecting demand sensing with product creation, assortment, seasonal launch timing and storytelling. Earlier signals can reduce the lag between a cultural movement and the products, creative and inventory required to act on it. Target is embedding AI elsewhere as part of a wider turnaround, including handheld tools for store teams, a rewritten shopping app completed in about 18 months with AI coding support, handwritten-list scanning and in-store item mapping. About one-third of store shoppers already use the app during visits. These investments arrive after fiscal 2025 net sales fell 1.7% and comparable sales declined 2.6%, so the technology must ultimately improve commercial performance rather than only process speed. For marketers, the case broadens the definition of AI marketing: the strongest advantage may come before campaign execution, when insight changes what gets made, stocked and presented to customers.",
    digestZh: "Target 正把 AI 用在广告之前，因为产品与商品决策决定了营销团队最终能够销售什么。内部平台 Trend Brain 同时分析时尚图片和社交媒体情绪，预测下一季可能升温的服装趋势。系统帮助设计师更快组合新概念，使系列更新速度接近过去的两倍，也能提前提示潜在滞销风险。Target 以波点趋势为例：早期信号让团队在趋势明显之前就增加相关商品投入。其营销价值在于把需求感知连接到产品开发、商品组合、季节发布节奏和内容叙事；更早的信号可以缩短文化变化与相应产品、创意和库存之间的时间差。作为转型的一部分，Target 还把 AI 用于门店员工手持工具、购物应用重构、手写清单识别和店内商品地图。借助 AI 编程工具，原本可能耗时数年的应用重构约 18 个月完成，目前约三分之一的到店顾客会在购物时使用该应用。这些投资发生在 2025 财年净销售下降 1.7%、同店销售下降 2.6% 之后，因此技术最终必须改善商业表现，而不只是提升流程速度。对营销人员而言，这个案例扩大了 AI 营销的定义：最重要的优势可能出现在活动执行前，当洞察真正改变品牌生产、备货和呈现给消费者的内容。",
    url: "https://www.marketingtechnews.net/news/target-uses-ai-to-predict-retail-trends-and-speed-product-decisions/", image: "",
  },
  {
    id: 33, category: "social", subcategory: "Social Media Case Study", platforms: ["TikTok", "Instagram", "YouTube"],
    source: "Marketing Brew", date: "February 13, 2026",
    title: "Inside Vita Coco’s ‘super fluid,’ organic-first social strategy",
    titleZh: "Vita Coco“超级灵活”的自然流量优先社交策略",
    summary: "Vita Coco’s always-on community response system turned a creator’s unsolicited jingle into 130,000 new TikTok followers, 245 million impressions and a four-year high in brand search.",
    summaryZh: "Vita Coco 的持续社区响应机制把创作者的自发歌曲变成 13 万新增 TikTok 粉丝、2.45 亿次曝光和四年来最高品牌搜索热度。",
    digest: "Vita Coco’s TikTok growth is built less on a fixed campaign calendar than on an operating model designed to notice and act on cultural opportunities quickly. The coconut-water brand crossed one million TikTok followers after collaborating with creator Romeo Bingham, whose earlier homemade Dr Pepper jingle had already attracted attention. Vita Coco responded early, commissioned a brand jingle and extended the idea through its online Super Bowl activity. In one month, the partnership added roughly 130,000 followers and pushed Google search interest for the brand to a four-year high. Bingham’s original Vita Coco video approached 40 million views, while follow-up Super Bowl and billboard content generated millions more. The company reports more than 245 million cumulative impressions. The important lesson is not simply to hire a viral creator. Vita Coco’s social and growth teams are structured to monitor comments, respond continuously and make decisions quickly. The same behaviour produced a one-day pop-up reacting to criticism of Poppi’s creator vending machines, generating owned engagement and user content. Its Coco Man mascot gives the brand a recognisable participant for conversations with other brand characters. The team reviews performance monthly but stays in constant contact with consumers between reviews. It is also preparing experiments in TikTok Shop and Live, with YouTube Shorts as a contingency. The case shows that organic-first marketing still requires infrastructure: a clear voice, empowered people, reusable brand assets and enough operational speed to turn an audience signal into a larger idea before the moment disappears.",
    digestZh: "Vita Coco 的 TikTok 增长并不主要依赖固定活动日历，而是建立在能够快速发现并利用文化机会的运营方式上。椰子水品牌在与创作者 Romeo Bingham 合作后突破 100 万 TikTok 粉丝；Bingham 此前因自制 Dr Pepper 广告歌受到关注。Vita Coco 很早就在评论区回应，随后邀请其创作品牌歌曲，并把创意延展到线上超级碗活动。一个月内，合作带来约 13 万新增粉丝，并使品牌 Google 搜索热度达到四年最高。Bingham 的首支 Vita Coco 视频接近 4000 万次观看，后续超级碗和户外屏幕内容又获得数百万观看；品牌称累计曝光超过 2.45 亿次。真正的启示不是简单寻找爆红创作者，而是 Vita Coco 的社交与增长团队被设计成持续监测评论、快速回应和及时决策。相同机制还让团队在一天内推出回应 Poppi 创作者售货机争议的快闪活动，带来品牌自有互动与用户内容。Coco Man 吉祥物则为品牌提供了参与跨品牌对话的固定角色。团队每月复盘表现，但复盘之间始终保持与消费者的连续联系，并准备测试 TikTok Shop、TikTok Live，同时把 YouTube Shorts 作为备选。案例说明，自然流量优先并不等于随意：它需要清晰语气、被授权的团队、可重复使用的品牌资产，以及在文化时刻消失之前把受众信号放大的运营速度。",
    url: "https://www.marketingbrew.com/stories/2026/02/13/vita-coco-social-media-strategy-tiktok-romeo-bingham", image: "",
  },
  {
    id: 34, category: "brand", subcategory: "D2C highlight",
    source: "Marketing Dive", date: "July 2, 2026",
    title: "How Tom Holland’s nonalcoholic Bero breaks through with brand partners",
    titleZh: "Tom Holland 联创的无酒精啤酒 Bero 如何借品牌合作突围",
    summary: "Bero uses Tom Holland’s founder story and partnerships with Chase, Barry’s and Aston Martin to turn lifestyle alignment into distribution, credibility and scaled media access.",
    summaryZh: "Bero 通过 Tom Holland 的创始人故事及与 Chase、Barry’s 和 Aston Martin 的合作，把生活方式契合转化为渠道、信任与规模化媒体资源。",
    digest: "Bero launched in late 2024 with actor Tom Holland as co-founder and a positioning that treats nonalcoholic beer as part of a balanced, aspirational lifestyle rather than a product defined only by what it removes. After entering Target in 2025, the brand reported nearly $10 million in first-year sales and expects revenue to more than double as distribution expands through Kroger, Publix, Erewhon and Amazon. Partnerships are doing several strategic jobs at once. Chase Sapphire first offered access to airport lounges and hospitality decision-makers, then expanded the relationship into Wimbledon events and an omnichannel business-card campaign spanning television, streaming, airports, outdoor, radio and social—media scale Bero could not have purchased alone. Barry’s connects the brand to performance, recovery and social gathering through a limited shandy-inspired shake. Aston Martin reinforces British provenance, craftsmanship and premium aspiration. These collaborations also bridge B2C and B2B marketing: consumers receive emotional lifestyle stories, while retailers, distributors and hospitality partners hear a founder-led entrepreneurial case. Holland’s sobriety journey provides credibility, but Bero deliberately avoids preaching exclusively to sober consumers. Its “100% Bero” platform reframes the category around taste, quality, refreshment and occasions gained rather than alcohol removed. The shandy, described as 70% lemonade and 30% Bero, expands both product appeal and drinking occasions. For emerging D2C brands, the case shows how a partnership should contribute more than borrowed attention: the strongest choices unlock a specific audience, distribution environment, cultural context or media capability while reinforcing the same central positioning.",
    digestZh: "Bero 于 2024 年底推出，由演员 Tom Holland 共同创立。品牌没有只用“不含酒精”定义产品，而是把无酒精啤酒定位为平衡、向上生活方式的一部分。2025 年进入 Target 后，品牌首年销售接近 1000 万美元，并预计随着 Kroger、Publix、Erewhon 和 Amazon 等渠道扩张，今年收入将增长一倍以上。合作伙伴同时承担多个策略任务。Chase Sapphire 最初帮助 Bero 进入机场贵宾室和酒店餐饮决策者网络，随后扩展到温网活动以及覆盖电视、流媒体、机场、户外、广播和社交的商业卡活动，为初创品牌提供其无法独立购买的媒体规模。Barry’s 通过以 Bero shandy 为灵感的限定奶昔，把品牌连接到运动表现、恢复和社交聚会；Aston Martin 则强化英国渊源、工艺和高端感。这些合作也连接 B2C 与 B2B：消费者看到情感化的生活方式故事，而零售商、经销商与酒店伙伴则听到创始人创业叙事。Holland 的戒酒经历带来可信度，但品牌并不只对完全戒酒者说教。“100% Bero”平台把重点从失去酒精转向获得口味、品质、清爽感和更多饮用场景；由 70% 柠檬水和 30% Bero 组成的 shandy 进一步扩大人群与场景。对新兴 D2C 品牌而言，案例说明合作不应只有借势曝光，优秀伙伴必须带来特定受众、渠道、文化语境或媒体能力，同时强化同一个核心定位。",
    url: "https://www.marketingdive.com/news/how-tom-hollands-nonalcoholic-beer-breaks-through-with-brand-partners/824215/", image: "",
  },
  {
    id: 35, category: "ai", subcategory: "Ad tech",
    source: "Marketing Dive", date: "July 23, 2026",
    title: "Google’s ads biz gets boost from World Cup hype, Gemini improvements",
    titleZh: "世界杯热度与 Gemini 升级推动 Google 广告业务增长",
    summary: "Gemini is improving ad relevance across Search and shopping while AI-curated YouTube sponsorships connect brands with live cultural moments, helping Google ad revenue rise 14% year over year.",
    summaryZh: "Gemini 正在提升搜索与购物广告的相关性，同时用 AI 为 YouTube 品牌赞助动态匹配文化热点，推动 Google 广告收入同比增长 14%。",
    digest: "Google’s second-quarter results offer a concrete view of how Gemini is moving from an experimental interface into the machinery of a mature advertising business. Alphabet reported that Google ad revenue increased 14% year over year to $81.6 billion, while Search and other revenue rose nearly 17% to $63.3 billion. Executives said Gemini improves Google’s ability to understand what people are looking for and match the right advertisement to that intent. In commerce campaigns, the company reported a 20% improvement in delivering highly relevant shopping ads. The development matters because it applies generative AI to the less visible but commercially decisive parts of media buying: interpreting queries, matching products and deciding which message belongs in a specific moment. YouTube is extending the same principle into culture-led advertising. World Cup content reached 1.7 billion unique viewers globally, and Google introduced custom sponsorships that use AI to surface videos aligned with a brand’s desired moment. YouTube ad revenue increased roughly 13% to $11 billion. As viewing moves toward connected television, Google is also testing two-click purchasing on the TV screen, bringing inspiration and transaction closer together. The results do not remove the risks surrounding AI investment: Google raised its expected 2026 capital expenditure range to $195–205 billion. For marketers, the useful signal is therefore not AI novelty alone, but measurable improvement in relevance, commerce and placement. The next test is whether brands can verify incremental outcomes while maintaining control over where AI places their message.",
    digestZh: "Google 第二季度业绩具体展示了 Gemini 如何从实验性界面进入成熟广告业务的核心机制。Alphabet 报告显示，Google 广告收入同比增长 14% 至 816 亿美元，其中搜索及其他业务收入增长近 17% 至 633 亿美元。管理层表示，Gemini 提升了平台理解用户意图并匹配合适广告的能力；在商业广告中，相关购物广告的投放效果改善了 20%。这一变化的重要性在于，生成式 AI 被用于媒介购买中不易被看见、却直接影响商业结果的环节：理解查询、匹配产品，以及判断某一时刻应出现什么信息。YouTube 也把同样思路延伸到文化热点广告。世界杯相关内容触达全球 17 亿独立观众，Google 推出定制赞助方案，通过 AI 动态找到与品牌目标时刻匹配的视频；YouTube 广告收入同比增长约 13% 至 110 亿美元。随着观看行为转向联网电视，Google 还在测试电视端两次点击即可完成购买，让内容启发与交易更接近。与此同时，AI 投资成本仍然巨大，Google 把 2026 年资本开支预期上调至 1950 亿至 2050 亿美元。对营销人员而言，真正值得关注的不是 AI 新鲜感，而是它是否能持续改善相关性、商业转化与媒介匹配，并让品牌验证增量效果、保持投放控制。",
    url: "https://www.marketingdive.com/news/googles-ads-biz-gets-boost-from-world-cup-hype-gemini-improvements/826008/", image: "",
  },
  {
    id: 36, category: "social", subcategory: "Social Media Case Study", platforms: ["TikTok", "Instagram"],
    source: "Marketing Brew", date: "January 12, 2026",
    title: "‘We all hate ads’: How Liquid Death is keeping social marketers on their toes",
    titleZh: "“我们都讨厌广告”：Liquid Death 如何让社交营销持续出其不意",
    summary: "Liquid Death treats social as an in-house comedy writers’ room, publishing fewer high-bar ideas, measuring shares over likes and rapidly amplifying the audience content that fits its voice.",
    summaryZh: "Liquid Death 把社交团队当作内部喜剧编剧室，以少而精的创意、分享量而非点赞量作为标准，并快速放大符合品牌语气的用户内容。",
    digest: "Liquid Death has built more than 14 million followers across TikTok and Instagram by running social media less like a campaign calendar and more like a comedy writers’ room. Its small in-house team includes professional comedians, and CEO Mike Cessario participates in weekly creative sessions. The group deliberately publishes only a few ideas each month because every post must meet a high entertainment threshold. Its goal is to “win the feed,” and shares—not likes—are the North Star because sharing shows that a viewer found the work worth passing to someone else. The operating model produced the Small Cans campaign, which generated 30 million views and a three-to-one ratio of shares to likes during its first 48 hours. A fighter-jet promotion similarly turned an intentionally absurd premise into sales and earned media. The brand also watches for unpaid, unprompted user content that already expresses its sensibility, then boosts the strongest examples rather than forcing every conversation through commissioned creators. Execution changes by platform: Instagram receives more polished work, while TikTok favors material that looks captured inside the culture of the feed. Liquid Death is also exploring TikTok Shop and affiliate relationships, linking entertainment more directly with purchase. The case shows that a chaotic public voice can rest on disciplined internal choices. A distinctive tone, senior creative involvement, tight quality control, a clear sharing metric and the authority to move quickly all make the spontaneity possible. Other brands cannot simply copy the jokes; they can copy the system that protects a recognizable point of view and rewards ideas audiences voluntarily distribute.",
    digestZh: "Liquid Death 在 TikTok 和 Instagram 上累计超过 1400 万粉丝，其社交运营不像传统活动日历，更像一个喜剧编剧室。小型内部团队包括专业喜剧演员，CEO Mike Cessario 也参加每周创意会议。团队每月只发布少数内容，因为每个创意都必须达到很高的娱乐标准。目标是“赢得信息流”，核心指标不是点赞而是分享，因为分享代表受众认为内容值得传给别人。这套方式催生了 Small Cans 活动，前 48 小时获得 3000 万次观看，分享与点赞比例达到三比一；战斗机促销也把刻意荒诞的设定转化为销售和媒体报道。品牌同时持续寻找未经邀请、自然出现的用户内容，只放大最符合品牌语气的部分，而不是把所有对话都变成付费创作者合作。不同平台采用不同表达：Instagram 更精致，TikTok 则更像原生捕捉的文化内容。品牌还在探索 TikTok Shop 与联盟合作，让娱乐更直接地连接购买。这个案例说明，看似混乱的外部语气背后其实需要严格的内部机制。鲜明语气、高层参与、清晰质量门槛、以分享为核心的衡量方式，以及快速行动的权限，共同创造了自发感。其他品牌不能照搬笑话，但可以借鉴这套保护独特观点、并奖励受众主动传播的系统。",
    url: "https://www.marketingbrew.com/stories/2026/01/12/liquid-death-social-marketing-strategy", image: "",
  },
  {
    id: 37, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Dive", date: "July 21, 2026",
    title: "Why Liberty Mutual turned a viral ad moment into a new brand character",
    titleZh: "Liberty Mutual 为什么把病毒广告片段变成全新品牌角色",
    summary: "Liberty Mutual turned the long-running “Liberty Biberty” mispronunciation meme into a physical puppet built for TV, creators, sports and events after testing it against more than 160 ideas.",
    summaryZh: "Liberty Mutual 把持续多年的“Liberty Biberty”口误梗变成实体木偶，并在 160 多个创意中验证后，将其延展到电视、创作者、体育与线下活动。",
    digest: "Liberty Mutual’s new Liberty Biberty character began with an accidental-looking line in a 2019 commercial. An actor repeatedly mispronounced the insurer’s name as “Liberty Biberty,” and the moment continued to circulate as a meme long after the original advertisement. Rather than simply reposting the old joke, the company turned it into a fuzzy physical puppet developed with Jim Henson’s Creature Shop. The decision followed a broad creative review: Liberty Mutual evaluated more than 160 advertisements and concepts and put the character through strong pre-market testing before committing to a larger role. The puppet now appears across television, streaming, social media and creator content, with extensions into NBC Sunday Night Baseball and ESPN SportsCenter. A physical character also gives the brand an asset that can appear at events and interact with people beyond the screen. Importantly, Liberty Biberty does not replace the established LiMu Emu and Doug duo. It expands the brand’s character system while preserving familiar memory structures. The campaign demonstrates how social listening can uncover durable brand equity inside an unintended audience response. But the team did not mistake virality for strategy: it validated recognition, built a high-quality execution partner around the idea and planned multiple contexts in which the character could remain useful. For marketers, the lesson is to treat memes as signals rather than finished campaigns. The strongest cultural reactions can become long-term assets when they are unmistakably connected to the brand, survive formal testing and are designed for repeated participation across media—not merely revived for a short burst of nostalgia.",
    digestZh: "Liberty Mutual 的新角色 Liberty Biberty 起源于 2019 年广告中的一个“意外”台词：演员反复把保险公司名称说成“Liberty Biberty”。这个片段在原广告结束很久后仍以网络梗形式传播。品牌没有只是重新发布旧笑话，而是与 Jim Henson’s Creature Shop 合作，把它变成毛绒实体木偶。这个决定经过了系统验证：Liberty Mutual 审核了 160 多支广告与概念，并在正式扩大投入前进行了表现良好的市场前测试。如今，这个角色进入电视、流媒体、社交与创作者内容，并延展到 NBC 周日晚间棒球和 ESPN SportsCenter。实体木偶也让品牌拥有一个可以在线下活动中与人互动的资产。重要的是，Liberty Biberty 并没有取代已经熟悉的 LiMu Emu 与 Doug，而是扩展角色体系，同时保留既有记忆结构。案例展示了社交聆听如何从意外的受众反应中发现长期品牌资产，但团队没有把病毒传播误当成完整策略：它验证了识别度，选择高质量制作伙伴，并设计了角色可以持续发挥作用的多种语境。对营销人员而言，网络梗应被视为信号而非成品活动。只有当文化反应与品牌紧密相关、通过正式测试，并能在多种媒体中持续参与时，它才可能从短期怀旧转化为长期资产。",
    url: "https://www.marketingdive.com/news/why-liberty-mutual-turned-a-viral-ad-moment-into-a-new-brand-character/825724/", image: "",
  },
  {
    id: 38, category: "ai", subcategory: "AI marketing tools",
    source: "Marketing Dive", date: "June 23, 2026",
    title: "Gap brings AI to owned marketing channels across brand portfolio",
    titleZh: "Gap 将 AI 引入旗下品牌的自有营销渠道",
    summary: "Gap is connecting customer and product data, agentic workflows and generative creative tools to personalize owned-channel experiences and speed campaign delivery across its retail portfolio.",
    summaryZh: "Gap 正连接客户与产品数据、智能体工作流和生成式创意工具，以个性化自有渠道体验，并加快整个零售品牌组合的营销交付。",
    digest: "Gap Inc. is treating AI as a marketing-operating-model project, rather than a standalone content tool. The retailer plans to modernize the shared marketing organization behind Gap, Old Navy, Banana Republic and Athleta through partnerships with Google Cloud, Zeta Global and Publicis Sapient. The first focus is owned channels: using AI to personalize experiences at scale, improve customer interactions and accelerate campaign delivery. Google Cloud is intended to unite customer and product intelligence so the organization can make better decisions across content, activations and ecommerce. Gap also plans to use Google’s Agent Studio, Agent Engine and Gemini models for workflows, together with Nano Banana for images and Veo for video production. Zeta’s Athena layer is positioned as the connection between data, decision-making and execution, including strategy, creative development, activation and optimization. Publicis Sapient’s role is broader still, spanning talent, process, data and partner ecosystems so the program can become more measurable and responsive to behavior. The lesson is that useful AI marketing is not only a faster asset factory. Its strongest role may be to connect signals, decisions and action across the customer journey, while creating more time for people to focus on strategy and storytelling. Gap’s plan is still an implementation announcement, not proof of final impact. Marketers should watch for evidence that personalization improves outcomes without fragmenting the brand, and that the new stack gives teams clearer responsibility rather than simply adding another layer of software.",
    digestZh: "Gap Inc. 把 AI 视为营销运营模式的改造，而不只是一个独立的内容工具。该零售集团计划借助 Google Cloud、Zeta Global 与 Publicis Sapient，更新服务于 Gap、Old Navy、Banana Republic 和 Athleta 的共享营销组织。第一阶段聚焦自有渠道：用 AI 大规模个性化体验、改善客户互动并加快活动交付。Google Cloud 将连接客户与产品情报，帮助团队在内容、营销触点和电商之间做出更好的决策；Gap 还计划使用 Agent Studio、Agent Engine 与 Gemini 模型来搭建工作流，并用 Nano Banana 生成图片、Veo 生成视频。Zeta 的 Athena 层被定位为连接数据、决策和执行的机制，覆盖策略、创意开发、活动启动和优化。Publicis Sapient 的工作则延伸到人才、流程、数据和伙伴生态，使整个项目更可衡量、更能响应消费者行为。这个案例的启示是，有价值的 AI 营销不应只是更快地生产素材；它更大的作用是把顾客旅程中的信号、决策和行动连接起来，同时为团队释放更多策略与叙事时间。Gap 目前公布的是实施计划，还不是最终效果证明。营销人员应继续关注个性化是否真正改善结果、不会稀释品牌，以及新技术栈是否让职责更清晰，而不是再增加一层软件。",
    url: "https://www.marketingdive.com/news/gap-brings-ai-to-owned-marketing-channels-across-brand-portfolio/823491/", image: "",
  },
  {
    id: 39, category: "social", subcategory: "Social Media Case Study", platforms: ["X", "Instagram"],
    source: "Marketing Brew", date: "June 22, 2026",
    title: "CeraVe’s Kevin Durant campaign led to a 43% sales lift—here’s how",
    titleZh: "CeraVe 的 Kevin Durant 活动如何带来 43% 销售增长",
    summary: "CeraVe built a social-first campaign around Kevin Durant’s long-running “ashy ankles” meme, using platform-native breadcrumbs and comedy to reach men with a credible product demonstration.",
    summaryZh: "CeraVe 围绕 Kevin Durant 长期流传的“干燥脚踝”梗打造社交优先活动，通过平台原生的铺垫内容和幽默表达，以可信的产品演示触达男性受众。",
    digest: "CeraVe’s “New Face of Legs” campaign shows how a brand can convert a real internet reference into a product story without making paid work feel detached from the culture that inspired it. The skincare brand wanted to grow among men, particularly men of color, and found a natural starting point in a 2021 viral post about NBA player Kevin Durant’s visibly dry legs. Durant already had a candid voice on X, where he often responds directly to fans. CeraVe let that behavior shape the execution: he addressed the old joke in a video, while the wider campaign used informal posts, paparazzi-style Instagram images and a hero film that turned moisturization into the punchline. Television, out-of-home and point-of-sale extended the idea, but social was the primary focus. The campaign generated a reported 43% sales lift, 4.1 billion PR impressions and 83 million organic video views. Its informal creative test was simple: would people share it in a group chat? That standard kept the work entertaining enough to travel beyond paid media. The result also benefited from a repeatable CeraVe playbook: seed ambiguity and small clues before revealing the full message, inviting people to participate in figuring it out. Medical influencers then broadened reach without sacrificing product credibility. The lesson is not to chase any meme, but to find one that fits a product truth, use the talent’s actual platform behavior, stage information people want to discuss, and reconnect attention to a demonstration that can move a business metric.",
    digestZh: "CeraVe 的“New Face of Legs”案例展示了品牌如何把真实的网络文化线索变成产品故事，同时不让付费内容脱离其灵感来源的文化语境。护肤品牌希望在男性、尤其是有色人种男性中扩大影响，因此选择了 2021 年围绕 NBA 球员 Kevin Durant 干燥双腿流传的网络梗。Durant 在 X 上本来就以直接回应粉丝而闻名，CeraVe 让这种真实的平台行为决定执行方式：他在视频中回应旧玩笑；更完整的活动则用看似随拍的 Instagram 图片、轻松的帖子和主影片，把保湿功效本身变成笑点。电视、户外和销售终端放大了创意，但社交是主要阵地。活动据称带来 43% 的销售增长、41 亿次公关曝光和 8300 万次自然视频观看。团队用一个简单标准判断创意：人们会不会把它分享到群聊？这让内容足够有趣，可以超越媒体购买自然传播。案例也体现了 CeraVe 可重复使用的方式：先投放模糊线索，再揭示完整信息，邀请受众参与猜测；医学类创作者则扩大传播，同时保持产品可信度。真正的启示不是随便追逐梗，而是寻找能对应产品事实的文化线索，使用人物真实的平台行为，分阶段释放值得讨论的信息，并将注意力重新连接到能够推动业务指标的产品演示。",
    url: "https://www.marketingbrew.com/stories/ceraves-kevin-durant-campaign-led-to-a-43-sales-lift", image: "",
  },
  {
    id: 40, category: "brand", subcategory: "Brand campaign",
    source: "Marketing Dive", date: "June 26, 2026",
    title: "Campaign Trail: The Honest Company delivers women’s bathroom truths",
    titleZh: "Campaign Trail：The Honest Company 直面女性的“浴室真相”",
    summary: "The Honest Company uses frank, humorous creative and a deliberately unexpected newspaper to make flushable wipes relevant to women while expanding the category beyond its male-coded conventions.",
    summaryZh: "The Honest Company 用坦率幽默的创意和一本出其不意的报纸，让可冲散湿巾与女性产生关联，并突破该品类长期偏男性化的表达方式。",
    digest: "The Honest Company’s “It’s Time to Get Honest” campaign is built around a clear category problem: flushable wipes were growing and reaching more retail doors, but the category still needed a convincing reason for women who habitually use toilet paper to consider it. The brand and agency Zambezi chose not to soften the topic. Instead, a 30-second film uses visual double entendres and direct language about bathroom realities, including periods and discharge, to normalize a conversation advertising has usually avoided. The campaign combines social, connected TV, out-of-home, influencer partnerships and a physical broadsheet called The Toilet Paper. The paper uses playful editorial formats—articles, horoscopes and listicles—to make the category message feel like culture rather than a product claim. It was distributed at selected Sugared + Bronzed locations, connecting the idea to a relevant beauty-service environment. The strategy draws support from research commissioned by the brand: 42% of surveyed women said they discuss bathroom experiences weekly. Honest treats openness as an existing behavior to join, not an attitude it must manufacture. Influencers add multiple touchpoints, but the campaign gives each one a frank creative point of view rather than asking them merely to repeat copy. The case shows how a challenger can create category relevance by naming the social tension everyone recognizes but few advertisers acknowledge. The work stays intimate and provocative without being needlessly crude, and makes a practical product benefit part of a wider permission structure: women can speak plainly about their everyday bodies.",
    digestZh: "The Honest Company 的“It’s Time to Get Honest”活动解决的是一个明确的品类问题：可冲散湿巾正在增长、进入更多零售渠道，但要让习惯使用卫生纸的女性真正考虑该产品，品牌还需要一个有说服力的理由。品牌与 Zambezi 没有选择淡化话题，而是在 30 秒影片中运用视觉双关和直接语言，谈论经期、分泌物等浴室现实，去正常化广告通常回避的对话。活动覆盖社交、联网电视、户外、创作者合作，并推出一本名为 The Toilet Paper 的实体大报。报纸采用文章、星座和榜单等趣味编辑形式，让品类信息更像文化内容而非产品硬广；它在部分 Sugared + Bronzed 门店发放，连接到相关的美容服务场景。品牌委托研究发现，42% 的受访女性每周都会谈论浴室经历。因此 Honest 不是凭空制造“坦率”，而是加入已经存在的受众行为。创作者合作提供多个接触点，但每个人都获得了坦率的创意观点，而非机械复述文案。这个案例的价值在于，它证明挑战者品牌可以通过说出人人都知道、但很少有广告主愿意承认的社会张力来建立品类相关性。创意保持亲近和大胆，却不过分粗俗，并把实用产品利益放进更大的许可中：女性可以坦然谈论日常身体经验。",
    url: "https://www.marketingdive.com/news/campaign-trail-the-honest-company-delivers-womens-bathroom-truths/823679/", image: "",
  },
  {
    id: 41, category: "ai", subcategory: "Ad tech", daily: true,
    source: "Marketing Brew", date: "July 17, 2026",
    title: "Advertisers testing ChatGPT are eager for more campaign control and measurement tools",
    titleZh: "测试 ChatGPT 广告的广告主期待更多投放控制与衡量工具",
    summary: "Early ChatGPT advertisers are borrowing search practices to test intent-rich queries, but they still need stronger controls and incrementality measurement before treating the channel as a scalable media buy.",
    summaryZh: "早期 ChatGPT 广告主正借鉴搜索广告方法测试高意图查询，但在将其视为可规模化媒体渠道前，仍需要更强的投放控制和增量衡量能力。",
    digest: "The article captures the practical reality behind the rush to test ChatGPT advertising. Brands such as Bark, ButcherBox and Vanta are not assuming that a new ad environment is automatically valuable; they are testing because their audiences already ask commercial questions in AI interfaces. Bark began advertising after seeing parents use ChatGPT, Gemini and Claude to ask questions such as whether Roblox is safe. ButcherBox applied the search terms and copy that have worked in Google campaigns, finding early traffic and click-through signals around protein, meal preparation and diet. The strategic distinction is that these are intent-led tests, not broad awareness buys. Yet the companies also describe a channel still missing several mature-market controls. Marketers want more ability to tune campaigns, clearer objectives, stronger reporting and a way to understand whether ChatGPT activity creates incremental outcomes rather than merely redistributing existing demand. Some teams are relying on UTMs and their own attribution systems while OpenAI develops broader measurement features. The article is useful because it gives a disciplined framing for emerging ad-tech adoption: follow the audience’s questions, start with a narrow use case, port only the lessons that fit the new context, and build your own measurement plan before the platform’s toolset catches up. Early performance indicators can justify learning, but not an automatic scale decision.",
    digestZh: "这篇文章呈现了测试 ChatGPT 广告背后的实际情况。Bark、ButcherBox 和 Vanta 等品牌并未因为它是新广告环境就默认其有价值；它们测试的原因是受众已经在 AI 界面提出商业问题。Bark 发现家长会在 ChatGPT、Gemini 和 Claude 中询问 Roblox 是否安全，因此开始投放。ButcherBox 则借用在 Google 搜索广告中验证过的关键词和文案，在蛋白质、备餐和饮食相关主题上看到了早期流量与点击率信号。关键在于，这些是由意图驱动的测试，而不是大范围的品牌曝光购买。但这些公司也指出，平台仍缺少成熟渠道的许多控制能力：广告主希望有更多调节投放的权限、更清晰的目标、更完整的报告，以及判断 ChatGPT 是否带来真正增量而非转移既有需求的方法。目前，一些团队依赖 UTM 和自有归因系统，等待 OpenAI 推出更多衡量功能。对营销人员而言，价值在于一套纪律化框架：先追随受众的问题，用狭窄场景开始测试，只迁移适合新环境的经验，并在平台工具完善前先建立自己的衡量计划。早期指标可以证明值得学习，但不能自动证明应当扩大投入。",
    url: "https://www.marketingbrew.com/stories/chatgpt-advertisers-seeking-campaign-control-measurement-tools", image: "",
  },
  {
    id: 42, category: "social", subcategory: "Social Media Case Study", platforms: ["Livestreaming", "Cross-platform"], daily: true,
    source: "Marketing Brew", date: "April 30, 2026",
    title: "A ‘new way of marketing’: Inside Expedia’s partnership with IShowSpeed",
    titleZh: "“一种新的营销方式”：Expedia 与 IShowSpeed 合作内幕",
    summary: "Expedia built a yearlong, social-first creator partnership around IShowSpeed’s real travel behavior, pairing an unpredictable livestream with a real-time clipping operation to distribute its best moments.",
    summaryZh: "Expedia 围绕 IShowSpeed 真实的旅行内容，打造为期一年的社交优先合作；它以不可预测的直播为核心，并通过实时剪辑团队分发最有传播力的时刻。",
    digest: "Expedia’s partnership with livestreamer IShowSpeed is a useful example of moving from a sponsored post to a creator-led media program. The travel company signed a yearlong relationship with the creator, whose audience spans about 150 million followers, and opened it with a nearly 12-hour stream across four Caribbean destinations. The format was intentionally different from polished travel advertising: it made the creator’s fast, curious and sometimes chaotic travel style the story, while still showing the practical moments viewers recognize, such as looking for a good meal after arriving somewhere new. Expedia and the creator spent six months planning the fit, emphasizing that neither side wanted a logo attached to unrelated content. The brand accepted the uncertainty of live video instead of trying to script it away. Its operational response was a real-time “war room” that clipped and distributed moments across social platforms as the livestream unfolded. That detail matters: a long live format only becomes a cross-platform content system when a team can identify, edit and circulate its strongest pieces while the audience is still paying attention. Expedia views this as a social-first model, and is expanding its broader influencer program internationally. For marketers, the case illustrates three requirements for durable creator work: select talent whose existing behavior naturally fits the category, commit long enough to build an unfolding story, and design the production and distribution infrastructure before the moment goes live. Authenticity here is not a lack of preparation; it is preparation that leaves room for the creator’s real personality and the audience’s real-time response.",
    digestZh: "Expedia 与直播创作者 IShowSpeed 的合作，是从一条赞助内容走向创作者主导媒体项目的有用案例。这家旅游公司与拥有约 1.5 亿跨平台粉丝的创作者签订了一年合作，并以近 12 小时、横跨四个加勒比目的地的直播开启。内容形式刻意不同于精致的旅游广告：创作者快速、好奇、甚至有些混乱的旅行方式本身成为故事，同时保留观众能理解的真实时刻，例如抵达后寻找一顿好饭。Expedia 与创作者花了六个月规划合作匹配度，双方都不希望只是把品牌 logo 放在无关内容上。品牌接受直播的不确定性，而不是试图把它完全写成脚本；为此建立了实时“战情室”，在直播过程中剪辑并分发最具传播力的片段。这个细节很关键：长直播只有当团队能在受众注意力仍在时识别、编辑和传播高光片段，才会成为跨平台内容系统。Expedia 将其视为社交优先模式，并扩大国际创作者计划。对营销人员而言，案例提出三项要求：选择本来就与品类相符的创作者、投入足够长的合作以形成持续叙事，并在直播前就设计好制作与分发机制。这里的真实性不是没有准备，而是准备得足够充分，给创作者真实个性和受众实时反应留下空间。",
    url: "https://www.marketingbrew.com/stories/2026/04/30/expedia-ishowspeed-partnership-creator-marketing-strategy", image: "",
  },
  {
    id: 43, category: "brand", subcategory: "Brand campaign", daily: true,
    source: "Marketing Dive", date: "July 22, 2026",
    title: "Hanes embraces risqué marketing in creative shakeup for basics brand",
    titleZh: "Hanes 以大胆营销重塑基础服饰品牌",
    summary: "Hanes’ “Get Comfortable” platform turns awkward everyday situations into a confidence promise, using a refreshed identity and playful creative to reposition a 125-year-old basics brand.",
    summaryZh: "Hanes 的“Get Comfortable”平台把日常尴尬场景转化为自信承诺，并通过焕新的品牌识别和幽默创意重新定位这个拥有 125 年历史的基础服饰品牌。",
    digest: "Hanes is using “Get Comfortable” to change the meaning of comfort from a functional clothing benefit into a social-confidence promise. The new work shows people in situations that would normally feel embarrassing—such as having their pants pulled down in a bar or shopping in underwear—yet staying unfazed because the brand’s basics make them feel good in their own skin. The idea is deliberately more provocative and entertaining than the brand’s earlier functional messaging. It appears across social, online video, retail, display and owned channels, supported by New York out-of-home executions and a refreshed logo that retains the brand’s red flag while updating the overall identity. The campaign follows HanesBrands’ $2.2 billion acquisition by Gildan Activewear and marks a major creative push with agency Special U.S. For marketers, the interesting move is not simply the risqué tone. It is the reframing of an established product truth—comfort—into an emotional benefit that can generate stories, visuals and a recognisable creative world. A heritage brand often struggles when its original functional promise becomes category table stakes. Hanes answers that problem by identifying an adjacent human outcome: the confidence to remain comfortable in public, even during uncomfortable moments. The campaign demonstrates how a brand refresh works best when design, message and media all reinforce the same behavioral idea, rather than treating a new logo as the strategy. Its success will depend on whether the humor stays distinctively Hanes and whether the broader platform continues to make basics feel culturally relevant.",
    digestZh: "Hanes 通过“Get Comfortable”把“舒适”从服装的功能利益转化为一种社交自信承诺。新广告展现了通常会让人尴尬的情境，例如在酒吧被拉下裤子或穿着内衣逛超市，但人物因为穿着 Hanes 基础服饰而依然从容。这个创意比品牌以往的功能性表达更大胆、更有娱乐性。活动覆盖社交、在线视频、零售、展示广告和自有渠道，并以纽约户外广告和更新后的 logo 支持；新识别保留了标志性的红旗元素，同时更新整体气质。该活动发生在 HanesBrands 被 Gildan Activewear 以 22 亿美元收购之后，也是品牌与 Special U.S. 合作的重要创意动作。对营销人员而言，有意思的不只是大胆语气，而是它如何把已经成熟的产品事实——舒适——重新定义为能产生故事、视觉和鲜明创意世界的情感利益。许多老品牌都会遇到原有功能承诺变成行业标配的问题，Hanes 的回应是找到相邻的人类结果：即使处于尴尬时刻，也能在公共场合保持自在的自信。案例表明，品牌焕新只有当设计、信息与媒介共同强化同一个行为概念时才最有效，而不是把更换 logo 当作策略。最终成效还要看这种幽默是否始终属于 Hanes，并让基础服饰继续保持文化相关性。",
    url: "https://www.marketingdive.com/news/hanes-embraces-risque-marketing-in-creative-shakeup-for-basics-brand/825871/", image: "",
  },
];
